hmrc/amls-frontend

- app/controllers/changeofficer/Flow.scala
- app/filters/ChangeOfficerFeatureFilter.scala
- test/filters/ChangeOfficerFeatureFilterSpec.scala
This PR implements a request filter that prevents the user from accessing the 'change nominated officer' flow when the feature is toggled off.
> AMLS-2828: Change officer flow

- run-local-no-inappconf.sh
Changed the order of operations in the shell script file to fix the Drop Save4Later issue which affected my locally running front end.
Updated script was tested on Jack's machine and still worked.
> Update shell script for running service locally to fix Save4Later issue

- app/views/msb/summary.scala.html
- test/controllers/msb/SummaryControllerSpec.scala
This work is to remove the ability to edit the “Do you send money to other countries?” question from the MSB summary page during a variation.
> AMLS-2934: Renewal Under Review - MSB - Page getting 404 on edit mode

- app/models/notifications/NotificationDetails.scala
- test/models/notifications/NotificationDetailsSpec.scala
Fixed this issue by refactoring the code that extracts the end date and reference number from the content, by switching to a regex-based strategy instead of string splitting.
> AMLS-2979: API11 is failing due to invalid date format & API11 content contains special characters

- app/config/ApplicationConfig.scala
- app/controllers/NotificationController.scala
- app/controllers/StatusController.scala
- app/utils/BusinessName.scala
- conf/application.conf
- test/controllers/NotificationControllerSpec.scala
- test/controllers/StatusControllerSpec.scala
- test/controllers/StatusControllerWithoutAmendmentsSpec.scala
- test/controllers/StatusControllerWithoutNotificationsSpec.scala
- test/utils/BusinessNameSpec.scala
* Added a feature toggle around contacting API 1b, defaulted to 'off'
* Refactored the code that retrieves the business name either from API 1b or from the data cache into a helper, and applied to `NotificationController`
* Refactored the status controller to also use this new helper + associated tests
> AMLS-2950: API 1b Business Name retrieval

- app/models/notifications/NotificationDetails.scala
- test/models/notifications/NotificationDetailsSpec.scala
This fixes an issue where responses to `getMessageDetails` calls are returning whitespace around the hyphens between special fields in the response. This PR adds in the capability to take this whitespace into account when extracting dates and reference numbers.
> AMLS-2979: API 11 Special characters

- app/controllers/payments/WaysToPayController.scala
- app/services/SubmissionResponseService.scala
- test/controllers/payments/WaysToPayControllerSpec.scala
- test/services/SubmissionResponseServiceSpec.scala
The main change here was to:
* Continue to send the AMLS ref number through to the getDetailedStatus call
* `getAmendment` now falls back to `getSubmission` if there was no amendment data
> Payment submission fix

- app/controllers/businessactivities/TransactionRecordController.scala
- test/controllers/businessactivities/TransactionRecordControllerSpec.scala
Primary change was to *not* ask how the user records transactions, if they're editing the 'Do you record transactions...' question, selected 'yes' and have already answered the following question.
> AMLS-3015: Refactored redirect targets for record transactions yes/no

- app/controllers/businessmatching/BusinessAppliedForPSRNumberController.scala
- app/controllers/businessmatching/CompanyRegistrationNumberController.scala
- app/controllers/businessmatching/RegisterServicesController.scala
- app/controllers/businessmatching/ServicesController.scala
- app/controllers/businessmatching/SummaryController.scala
- app/controllers/businessmatching/updateservice/ChangeServicesController.scala
- app/services/businessmatching/BusinessMatchingService.scala
- app/views/businessmatching/business_applied_for_psr_number.scala.html
- app/views/businessmatching/company_registration_number.scala.html
- app/views/businessmatching/register_services.scala.html
- app/views/businessmatching/services.scala.html
- app/views/businessmatching/updateservice/change_services.scala.html
- app/views/businessmatching/updateservice/remove_activities.scala.html
- test/controllers/businessmatching/BusinessAppliedForPSRNumberControllerSpec.scala
- test/controllers/businessmatching/RegisterServicesControllerSpec.scala
- test/controllers/businessmatching/ServicesControllerSpec.scala
- test/controllers/businessmatching/updateservice/ChangeServicesControllerSpec.scala
- test/views/businessmatching/business_applied_for_psr_numberSpec.scala
- test/views/businessmatching/company_registration_numberSpec.scala
- test/views/businessmatching/register_servicesSpec.scala
- test/views/businessmatching/servicesSpec.scala
- test/views/businessmatching/updateservice/change_servicesSpec.scala
Tended to be broken when going through the 'new service variation' flow as opposed to coming in through business matching as a new user.
> AMLS-2981: Fixed 'back to registration progress' link on several pages

- app/controllers/businessmatching/BusinessAppliedForPSRNumberController.scala
- app/controllers/businessmatching/RegisterServicesController.scala
- app/controllers/businessmatching/ServicesController.scala
- app/controllers/businessmatching/SummaryController.scala
- app/controllers/responsiblepeople/TrainingController.scala
- app/models/businessmatching/BusinessMatching.scala
- app/services/LandingService.scala
- app/services/businessmatching/BusinessMatchingService.scala
- test/controllers/businessmatching/BusinessAppliedForPSRNumberControllerSpec.scala
- test/controllers/businessmatching/RegisterServicesControllerSpec.scala
- test/controllers/businessmatching/ServicesControllerSpec.scala
- test/controllers/businessmatching/SummaryControllerSpec.scala
- test/models/businessmatching/BusinessMatchingSpec.scala
- test/services/businessmatching/BusinessMatchingServiceSpec.scala
This flag was added as there's currently no other way to tell whether the user has initially completed the business matching section or not.
This was playing havoc with the 'return to application progress' links inside business matching, which was previously based on the 'hasAccepted'
flag being true. Problem is, the state of that flag changes as you go through and edit the questions in business matching, meaning that the
registration progress link would appear to show randomly on some pages and not others. This should hopefully fix that.
I've taken care to make sure that the flag is defaulted to true when the data is read from API 5.
> AMLS-2981: Added new 'preAppComplete' flag to Business Matching

- app/controllers/bankdetails/BankAccountNameController.scala
Looks like the view was renamed from `bank_account_details` to `bank_account_name`, so the code has been updated accordingly.
> AMLS-3138: Fixed broken compilation

- app/utils/BusinessName.scala
- app/views/status/status_supervised.scala.html
To protect users from a failing API 1b call, `BusinessName` has been modified so that it falls back to using the name in the cache if the call to API 1b (through AMLS middle tier) fails.
> Business Name cache fallback

- app/config/ApplicationConfig.scala
- app/connectors/AuthConnector.scala
- app/models/enrolment/EnrolmentKey.scala
- app/models/enrolment/EnrolmentStoreEnrolment.scala
- app/modules/Module.scala
- app/services/AuthEnrolmentsService.scala
- test/connectors/AuthConnectorSpec.scala
- test/connectors/EnrolmentStoreConnectorSpec.scala
- test/models/enrolment/EnrolmentKeySpec.scala
- test/models/enrolment/EnrolmentStoreEnrolmentSpec.scala
This PR includes:
* Various models (+ specs) required for the new enrolment call
* Refactored AuthConnector to support DI
* Added `userDetails` method to AuthConnector
> AMLS-3238: Replace GG admin enrol with BAS TAX enrolment 

- app/services/SubmissionResponseService.scala
- app/typeclasses/confirmation/ConfirmationBreakdownRows.scala
- app/typeclasses/confirmation/ResponsiblePeopleRows.scala
To reduce the chaos in the submissionResponseService, typeclasses have been created and implement to construct breakdownRows for the various submission statuses
No logic has been added or removed, simply shifted and shared therefore, momentarily, unit tests remain in submissionResponseSpec rather than extracted to a typeclassSpec
> Amls 3222 typeclasses

- app/controllers/bankdetails/BankAccountAddController.scala
- app/controllers/bankdetails/WhatYouNeedController.scala
- app/models/bankdetails/BankDetails.scala
- app/views/bankdetails/what_you_need.scala.html
- conf/bankDetails.routes
- test/controllers/bankdetails/BankAccountAddControllerSpec.scala
- test/controllers/bankdetails/WhatYouNeedControllerSpec.scala
- test/generators/bankdetails/BankDetailsGenerator.scala
- test/models/bankdetails/BankDetailsSpec.scala
- test/views/bankdetails/what_you_needSpec.scala
* Page now correctly routes to either 'bank account name' or 'does this business have a bank account' based on current data
* Removed `index` querystring parameter
* Created a set of ScalaCheck generators for `BankDetails`
> AMLS-3904 Updated flow from 'What you need' page

- app/views/bankdetails/has_bank_account.scala.html
This is for the radio buttons on the Bank Details 'Does this business use a bank account?' page.
> AMLS-3931 Corrected styling for inline radio buttons

- app/controllers/bankdetails/WhatYouNeedController.scala
- app/controllers/bankdetails/YourBankAccountsController.scala
- app/models/bankdetails/BankDetails.scala
To do this, all of the common bank account filters (deleted, completed and visible accounts) have been extracted to a common location inside the BankDetails model.
> AMLS-3932 Filtered out 'no bank account' types

- app/controllers/bankdetails/BankAccountTypeController.scala
- app/controllers/bankdetails/HasBankAccountController.scala
- app/models/bankdetails/BankDetails.scala
- test/controllers/bankdetails/YourBankAccountsControllerSpec.scala
The 'Your Bank Accounts' page makes use of this filter, thus empty bank accounts should now be hidden from that view.
Also tidied up a couple of the controllers with the `bankdetails` package to rid the 'cyclomatic complexity' warnings.
> AMLS-3948 Included empty bank accounts in the `visibleAccounts` filter

- app/models/bankdetails/BankDetails.scala
- test/controllers/bankdetails/YourBankAccountsControllerSpec.scala
It now caters for the fact that a bank detail model might be empty but hasAccepted = true, which is the case for the data in the QA environment.
> AMLS-3948 Altered 'empty bank details' filter

- project/FrontendBuild.scala
- project/MicroService.scala
- project/plugins.sbt
Bumped library versions according to service catalogue.
Platform libraries are periodically updated, and service teams are required to keep up to date with progression of these libraries. This PR updates our platform libraries to be in line with the latest available.
There are related PRs for `amls` and `amls-notification`, but none of these pull requests are dependent on each other:
https://github.com/hmrc/amls-notification/pull/40
https://github.com/hmrc/amls/pull/192
* Successful unit test run
* Partial acceptance smoke test to verify that services start and run
- [ x ] Build passing.
- [ x ] Requires acceptance test run.
- [ x ] Appropriate labels added.
> Bumped library versions according to service catalogue

- project/FrontendBuild.scala
Bumped version of `frontend-bootstrap` to 8.26.0 according to the [service catalog library report](https://catalogue.tax.service.gov.uk/service/amls-frontend)
n/a
* Unit test suite run
* Smoke test through partial acceptance test regression run
> Bumped library version according to service catalogue

- app/controllers/LandingController.scala
- test/controllers/LandingControllerSpec.scala
Since migrating to Mongo, it does not make sense to the use the ShortLivedCache.remove method, as this only removes data from Save4Later.
This commit changes that to remove it from the data cache connector, which will ultimately remove the data from Mongo and Save4Later.
This could potentially fix a live issue we're seeing where the start page constantly redirects to itself.
n/a
On `master`, manually removed data from the database and ran `/`, which resulted in a redirect loop. Switched to the hotfix branch and re-ran the test, confirmed that the user is now correctly redirected to the business matching section without a redirect loop.
> HOTFIX: Remove cache from the right place on redirect

- app/connectors/cache/DataCacheConnectorMigrator.scala
- test/connectors/cache/DataCacheConnectorMigratorSpec.scala
This fixes a live issue where users coming into the service for the first time (or at least having not previously submitted) would constantly have their Save4Later data migrated whenever a database read was performed.
To fix this, the Save4Later cache is now removed when the migration has completed, which means that there is no longer anything to migrate from once it has been done once and their data would never again be overwritten.
n/a
* Manual testing locally by creating some data in Save4Later, turning Mongo 'on' and then attempting to fill out an additional section of the application
* Unit testing to verify that the data in `fallbackCache` is removed once the migration has taken place
> AMLS-4219: Remove Save4Later cache entry on migration event

- app/controllers/businessmatching/RegisterServicesController.scala
- app/services/businessmatching/BusinessMatchingService.scala
- test/controllers/businessmatching/RegisterServicesControllerSpec.scala
Amended the register services controller to remove the sections from mongo for any activities which were previously there, but have been removed. Also added logic to remove the supervision section if either ASP or TCSP had previously been there, but would no longer. 
Unit and Manually Tested
Regression Acceptance Tests run
> Amls 3884 - Clear section data when changing business activities for new submissions

- app/views/businessmatching/confirm_postcode.scala.html
The removal of the return to application progress link in a preApp page. (Link should never of been there)
> AMLS-3636 | Removed returnLink from preApp postcode page

- app/controllers/hvd/ExpectToReceiveCashPaymentsController.scala
- test/controllers/hvd/ExpectToReceiveCashPaymentsControllerSpec.scala
When user is trying to submit page without selecting any of possible options there should be an error displayed above checkbox group (error-notification rendered). In this pull request there's a fix for this issue which was discovered on expect_to_receive page for High Value Dealers. Error notification need to be displayed in order to generate Google Analytics event for an error.
none
- manual tests
- unit tests
- regression run
- need to be additionally tested in QA where the GA events can be tracked
> AMLS-4516 | Bug fix

- app/controllers/LandingController.scala
- test/controllers/LandingControllerSpec.scala
Fix error fetching Subscription from cache. Error was preventing the login events page from showing on logout and log back in. Removed try catch that was swallowing the error and always forcing redirect to the status page. 
N/A
Manual, Unit and Acceptance test.
> Amls 4558 achi

- app/views/confirmation/breakdown.scala.html
- app/views/confirmation/confirmation_new.scala.html
Bug fix: Table caption not read out when reading whole page. Changed caption to span with ariaDescribedBy. Added scopes for headers to be readout using other screen readers than VO ex. JAWS. VO is not supporting scopes.
none
- manual tests
- unit tests run
> Amls 4471 | Bug Fix: Fees table (accesibility)

- app/controllers/changeofficer/NewOfficerController.scala
- release_notes/AMLS-3717.txt
- test/controllers/changeofficer/NewOfficerControllerSpec.scala
- test/generators/ResponsiblePersonGenerator.scala
- test/models/responsiblepeople/ResponsiblePersonSpec.scala
Updated NewOfficerController to only display complete responsible people. Updates to spec required, and updates to ResponsiblePersonGenerator in order to test with complete / incomplete people.
NA
Passes spec tests and regression tests
- [ dd] Requires acceptance test run.
> AMLS-3717 | New Officer Controller validation

- app/views/tradingpremises/your_trading_premises.scala.html
- release_notes/AMLS-4728.txt
- test/views/tradingpremises/your_trading_premisesSpec.scala
If there is an incomplete trading premises in the list of Your trading premises. The button now reads "Return to application progress" 
If all trading premises are complete the button reads "Accept and complete section"
Manually
May need acceptance test check/run - Left checkbox blank
> Amls 4728 - Updated YTP "continue" button content

- app/views/responsiblepeople/legal_name_change_date.scala.html
- release_notes/AMLS-4628.txt
Simple change - added visually hidden label to date field in legal_name_change_date.scala.html, as per other date fields on site, so label is now read out by VO.
Passed spec tests, tested using MacOS VO
> AMLS-4628 | Added visually hidden label for form on "name change" page

- app/controllers/supervision/ProfessionalBodyMemberController.scala
- release_notes/AMLS-4603.txt
- test/controllers/supervision/ProfessionalBodyMemberControllerSpec.scala
Flow break when going back on question: Which professional body are you a member of? was fixed by changing redirection conditions in ProfessionalBodyMemberController.
- none
- manually
- regression sections involving supervision
> AMLS-4603 | Bug fix

- app/controllers/supervision/SummaryController.scala
- app/utils/ControllerHelper.scala
- app/views/supervision/summary.scala.html
- release_notes/AMLS-4796.txt
- test/controllers/supervision/SummaryControllerSpec.scala
- test/utils/ControllerHelperSpec.scala
Steps to recreate in the ticket with the same number.
User navigating through the flow, then clicking back could get to the state when the supervision section is incomplete and clicking back to the summary page caused the error because of missing data.
To avoid this change has been implemented to display summary page only when Supervision section is  complete. In other cases user is being redirected to progress page. 
If as result of clicking back supervision section will get to incomplete state user will see that on progress page.
- none
- unit tests
- manual tests
- regression run (supervision elements)
> AMLS-4796 | Supervision bug fix

- app/controllers/changeofficer/NewOfficerController.scala
- release_notes/AMLS-4772.txt
- test/controllers/changeofficer/NewOfficerControllerSpec.scala
As above. Full description of issue in the ticket. 
Fixed it by filtering rp's before updating nominated officer entry.
none
manually and unit tests
> AMLS-4772 | Bug fix: empty responsible people when trying to change nominated officer

- app/controllers/RegistrationProgressController.scala
- release_notes/AMLS-4815.txt
- test/controllers/RegistrationProgressControllerSpec.scala
As in the title. Now for approved application status is displayed Add or remove service.
none
manually checked and by unit testing
> AMLS-4815 | Changed 'Check details' to say 'Add or remove service' for approved application

- app/views/include/forms2/country_autocomplete.scala.html
- release_notes/AMLS-4821.txt
- test/views/include/country_autocompleteSpec.scala
Country lookup field should retain invalid entry when showing validation error messages. In this PR there is small change to country_autocomplete component which allows to do that.
- none
- manually
- unit tests
> AMLS-4821 | Fix - Country lookup field

- app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala
- test/controllers/businessmatching/updateservice/RemoveBusinessTypeHelperSpec.scala
On removing BPS or TDI an exception is thrown and logged in Kibana. While the flow still completes; this is a bad experience for the end user. This PR adds a generic catch all where a given sector does not exist in the cache for removal. 
N/A
Local + Unit + Regression.
> Amls 4917 - Error removing BPS or TDI

- app/models/moneyservicebusiness/SendTheLargestAmountsOfMoney.scala
- app/models/renewal/SendTheLargestAmountsOfMoney.scala
- app/services/LandingService.scala
- app/views/msb/send_largest_amounts_of_money.scala.html
- app/views/msb/summary.scala.html
- release_notes/AMLS-4838.txt
- test/controllers/msb/SendMoneyToOtherCountryControllerSpec.scala
- test/controllers/msb/SendTheLargestAmountsOfMoneyControllerSpec.scala
- test/controllers/msb/SummaryControllerSpec.scala
- test/models/moneyservicebusiness/MoneyServiceBusinessSpec.scala
- test/models/moneyservicebusiness/SendTheLargestAmountsOfMoneySpec.scala
- test/models/renewal/ConversionsSpec.scala
- test/services/LandingServiceSpec.scala
- test/services/UpdateMongoCacheServiceSpec.scala
- test/views/msb/send_largest_amounts_of_moneySpec.scala
- test/views/msb/summarySpec.scala
In this pull request there are implemented changes to SendTheLargestAmountsOfMoney model in order to display validation messages in similar way like it was done for MostTransactions. Updates to model, view, controller, specs and conversion methods. Loaded applications saved before changes and submitted them without problem, looks like there are no issues with compatibility.
- PR in acceptance tests for that
- unit tests
- manual checks
- regression
> Amls 4838 - Bug fix: Validation error messages not linked to group on MSB 'Where do you send the largest amounts of money' page

- project/FrontendBuild.scala
- test/utils/DateHelperSpec.scala
- test/utils/FeeRateHelperSpec.scala
Remove hmrctest lib as soon to be deprecated. 
N/A
Unit
> Remove depricated HMRC test lib

- app/models/estateagentbusiness/PenalisedUnderEstateAgentsAct.scala
- app/models/estateagentbusiness/ProfessionalBody.scala
- app/models/estateagentbusiness/RedressScheme.scala
- conf/messages
- release_notes/AMLS-4926.txt
- test/models/estateagentbusiness/PenalisedUnderEstateAgentsActSpec.scala
- test/models/estateagentbusiness/ProfessionalBodySpec.scala
Updated error messages in EAB flow. Added validation to redress scheme name input box - this will affect possibly some users who entered invalid characters in answer for this question. When they go to edit this question then additional validation rule will be applied - they will have to change their answer accordingly. 
- none
- manual checks
> AMLS-4926 | New error messages in EAB flow

- app/views/businessmatching/summary.scala.html
- release_notes/AMLS-5142.txt
- test/controllers/businessmatching/SummaryControllerSpec.scala
This ticket was to make sure the PSR and CRN questions within business matching are editable no matter what state they are in. Hence removing the pending status toggles.
Manual
Unit
> Amls 5142 - Making certain BM questions editable when pending approval

- app/models/renewal/Renewal.scala
- release_notes/AMLS-5214.txt
- test/models/renewal/RenewalSpec.scala
Live bug fix - users cannot load renewals when selected no on customers outside uk question.
- none
- unit tests, manually, regression
> AMLS-5214 Live bug fix customers outside uk

- conf/messages
- release_notes/AMLS-5211.txt
Update H1 from: 'What percentage of your turnover do you expect to come from cash payments of over €10,000?' to 'What percentage of your turnover came from cash payments of €10,000 or more? in HVD.
No related / dependant PR's.
This has been tested manually.
> AMLS-5211: Amended h1 title

- app/views/include/forms2/errorSummary.scala.html
- release_notes/AMLS-5071.txt
Remove ARIA role of tooltip from error summary list items
Locally: Manual/Unit/Acceptance
> Amls 5071 - Remove ARIA role of tooltip from error summary list items

- app/views/error.scala.html
- release_notes/AMLS-5220.txt
Add H1 to standard error page for tracking.
N/A
Local
> Add H1 to standard error page for tracking.

- app/models/FormTypes.scala
- app/models/responsiblepeople/PersonAddress.scala
- release_notes/AMLS-5209.txt
On the following questions, mandatory fields where only spaces are entered are no longer valid:
- Where does Jane Doe live?
- What was Jane Does previous address?
- What was Jane Does other previous address?
Manual testing
> AMLS-5209 | RP address rejects spaces in mandatory fields

- app/controllers/msb/MostTransactionsController.scala
- app/controllers/msb/SendTheLargestAmountsOfMoneyController.scala
- app/controllers/msb/WhichCurrenciesController.scala
- app/controllers/renewal/CustomersOutsideUKController.scala
- app/controllers/renewal/MostTransactionsController.scala
- app/controllers/renewal/SendTheLargestAmountsOfMoneyController.scala
- app/controllers/renewal/WhichCurrenciesController.scala
- release_notes/AMLS-5294.txt
- test/controllers/msb/MostTransactionsControllerSpec.scala
- test/controllers/renewal/MostTransactionsControllerSpec.scala
- test/controllers/renewal/WhichCurrenciesControllerSpec.scala
Fixed the handling of invalid input on countries and currencies pages. Empty fields are stripped out of the form data used to repopulate pages when invalid data has been inputted - this aligns the user's input with the errors displayed by the page.
Ran and amended unit tests, manual testing
> AMLS-5294 | Invalid input not working correctly on countries and currency pages

- app/config/ApplicationConfig.scala
- app/models/ViewResponse.scala
- app/models/amp/Amp.scala
- app/models/asp/Asp.scala
- app/models/businessmatching/updateservice/UpdateService.scala
- app/models/estateagentbusiness/EstateAgentBusiness.scala
- app/models/hvd/Hvd.scala
- app/models/moneyservicebusiness/MoneyServiceBusiness.scala
- app/models/responsiblepeople/ResponsiblePerson.scala
- app/models/supervision/Supervision.scala
- app/models/tcsp/Tcsp.scala
- app/models/tradingpremises/TradingPremises.scala
- test/models/amp/AmpSpec.scala
Fixed some uninitialised variable warnings (moved use of Reads below declaration in models), and the use of deprecated Play.current in Amp (moved URLs to ApplicationConfig and removed redundant superclass)
Ran spec tests
> Fixing warnings

- app/models/FormTypes.scala
- app/models/tradingpremises/ActivityStartDate.scala
- conf/messages
- release_notes/AMLS-4983.txt
- test/models/tradingpremises/ActivityStartDateSpec.scala
Validation now allows dates between 1700 and 2099 for activity start date in trading premises section for individual trading premise.
- for this to work with backend service need to be implemented schema change for appropriate field
- manually, unit tests (however submissions, amendments will not work without proper schema in place)
> Amls 4983 - Extended date validation for start date for trading premises

- app/views/confirmation/confirm_amendvariation.scala.html
- app/views/confirmation/confirm_renewal.scala.html
- app/views/confirmation/confirmation_new.scala.html
- conf/messages
- public/print.css
- release_notes/AMLS-5369.txt
- test/controllers/ConfirmationControllerSpec.scala
- test/views/confirmation/AmendmentConfirmationViewSpec.scala
- test/views/confirmation/RenewalConfirmationViewSpec.scala
- test/views/confirmation/SubmitRegistrationConfirmationViewSpec.scala
1. Content updated
2. Print link added (table link hidden if not expanded, as per discussion with Martin Underhill)
3. Button already reads "Continue to payment"
4. GA tracking added, using "fee-reference:click:print"
Manual tests, updated spec tests
> AMLS-5369 | Updated Fee & Ref content, added print link and GA tracking

- app/controllers/businessmatching/updateservice/add/NeedMoreInformationController.scala
- app/views/businessmatching/updateservice/add/new_service_information.scala.html
- conf/messages
- release_notes/AMLS-5420.txt
- test/views/businessmatching/updateservice/add/new_service_informationSpec.scala
Hide "supervision details" on "Update other information" page if section is complete.
"Supervision details" is shown on the "You need to update other information" page, if either ASP or TCSP is added and the supervision details section is not completed.
If only one service is added, it will read (where [text in brackets] is conditional on supervision details being complete):
"_You’ll need to complete the SERVICE [and supervision details] section[s]_".
If more than one is added, the services and "supervision details" will be displayed in bullet points.
"_You’ll need to complete the following sections:_
- _accountancy service provider_
- _trust or company service provider_
- _[supervision details]_"
Manual testing, updated unit tests
> AMLS-5420 | Hide "supervision details"

- app/utils/ActivitiesHelper.scala
- release_notes/AMLS-5476.txt
As above. Included AMP in sectors for which RP need to have AC. 
- first to be merged: https://github.com/hmrc/amls-stub/pull/137
- manually
> Amls 5476 - Bug fix: Approval fee is not rendering in fees table for amp people

- app/controllers/estateagentbusiness/ServicesDateOfChangeController.scala
- release_notes/AMLS-5501.txt
- test/controllers/estateagentbusiness/ServicesDateOfChangeControllerSpec.scala
EAB should redirect to redress scheme from date of change when editing services and Residential is selected.  
N/A
Local + Unit
> EAB Services date of change redirect to redress scheme fix

- app/services/cache/MongoCacheClient.scala
Reverted changes to mongo cache client made when removing bootstrap and upgrading frontend to play 2.5.19 and later to 2.6
- none
- manually
- unit tests
- regression
> AMLS-5365 | Reverting mongo cache client changes.

- app/views/businessdetails/activity_start_date.scala.html
- app/views/changeofficer/remove_responsible_person.scala.html
- app/views/date_of_change.scala.html
- app/views/hvd/cash_payment_first_date.scala.html
- app/views/include/forms2/date.scala.html
- app/views/include/forms2/input.scala.html
- app/views/responsiblepeople/address/new_home_date_of_change.scala.html
- app/views/responsiblepeople/date_of_birth.scala.html
- app/views/responsiblepeople/legal_name_change_date.scala.html
- app/views/responsiblepeople/position_within_business_start_date.scala.html
- app/views/responsiblepeople/remove_responsible_person.scala.html
- app/views/supervision/supervision_end.scala.html
- app/views/supervision/supervision_start.scala.html
- app/views/tradingpremises/activity_start_date.scala.html
- app/views/tradingpremises/agent_name.scala.html
- app/views/tradingpremises/remove_trading_premises.scala.html
- release_notes/AMLS-5622.txt
This ticket was to add aria-described-by to fieldset list of parameters - but it was already there but used in not right way. So in this PR after discussion with @tempertemper we've decided to get rid of example parameter in date template. It was necessary because both -example- as well as -hintText- parameters were basically doing the same thing.
Now only hintText is being used where necessary to provide hint and there's correct link to aria-described-by.
- none 
- manually
> Amls 5622 | Fixed aria-described-by in date fieldsets

- app/controllers/StatusController.scala
- app/services/RenewalService.scala
- release_notes/AMLS-5796.txt
- test/controllers/StatusControllerSpec.scala
We've identified what's causing a number of errors we didn't understand why were happening.
The errors;
```
Cannot get business matching or renewal date
Unable to redirect from Turnover page
Unable to retrieve SafeID from reviewDetails
Could not match activities against given options
```
I believe are being caused by the same problem.
When investigating in local dev I found that you could bypass the landing controller (bit that checks if the cache should be reloaded from API5) by bookmarking the application status page and going to that bookmark while already signed in to GG in an active session.
If I login in one window; then close the window and drop the cache (replicate the 30 day expiry); then hit my application status book mark the service does not reload the cache. The page renders …
> Amls 5796 - Cache validation and refresh from API5 if no cache when hitting status controller

- app/models/bankdetails/BankAccountSubsteps.scala
- release_notes/AMLS-5839.txt
- test/models/bankdetails/AccountSpec.scala
Reverts hmrc/amls-frontend#1399
Potentially writing sort code and account number into the incorrect fields in mongo.
> Revert "Amls 5839 - Reordered error message UK bank account"

- app/views/include/forms2/date.scala.html
- release_notes/AMLS-5096.txt
- test/views/include/dateSpec.scala
This is a fix to add whitespace to the aria-described-by field on date pages when there is an error and hint text,
Manually
Unit
> AMLS-5906 | Bug fix for aria described by whitespace

- app/models/renewal/Conversions.scala
- app/models/renewal/SendMoneyToOtherCountry.scala
- release_notes/AMLS-5894.txt
- test/models/renewal/ConversionsSpec.scala
- test/services/SubmissionServiceSpec.scala
This will fix the problem with empty lists being send while renewing the application.
Initial thoughts were that we are creating empty lists in frontend, but after small investigation I've found that we are missing one question when converting renewal data to subscription request. This was the problem. Because of that the AMLS while creating the request was using not updated data for this question and was creating empty lists in result.
- none
- manually
- regression
- unit tests
> Amls 5894 | Fix for empty countries lists in renewal

- app/controllers/LandingController.scala
- app/controllers/businessdetails/ConfirmRegisteredOfficeController.scala
- app/controllers/businessmatching/ConfirmPostCodeController.scala
- app/models/Country.scala
- app/models/FormTypes.scala
- app/models/businesscustomer/ReviewDetails.scala
- app/models/businessmatching/ConfirmPostcode.scala
- app/views/businessmatching/confirm_postcode.scala.html
- conf/messages
- release_notes/AMLS-5759.txt
- test/controllers/LandingControllerWithoutAmendmentsSpec.scala
- test/controllers/businessdetails/ConfirmRegisteredOfficeControllerSpec.scala
- test/controllers/businessmatching/ConfirmPostCodeControllerSpec.scala
- test/models/businessmatching/ConfirmPostcodeSpec.scala
- test/models/businessmatching/ReviewDetailsSpec.scala
In this PR there are significant changes to the flow from LandingController depending on the postcode/country code. There are also other changes, so please review carefully :D I've left some comments in this PR in a few places.
Testing:
1. Clone business-customer-stub
2. In EtmpController manipulate address as you like:
val address = Address("23 High Street", "Park View", Some("Gloucester"), Some("Gloucestershire"), Some("NE98 1ZZ"), "GB")
3. Stop this microservice in service manager
4. Run cloned service on 9926
5. Load empty application with IR-SA/UTR/1111111111 preset
6. You will land on Check this is the business you want to register and it should display adress modified above
7. Continue with testing
- none
- manually (using business-customer-stub)
- unit tests
> Amls 5759 | Update H1 on Confirm the postcode page in pre-application and improve routing

- conf/messages
mesasges file should have message for new renewal reminder as notifications.subject.v5.NewRenewalReminder but in the file it was notifications.subject.NewRenewalReminder
> DLS fix message for new renewal reminder

- app/views/include/forms2/anchor.scala.html
- Go to the [fit and proper test check page](http://localhost:9222/anti-money-laundering/responsible-people/fit-and-proper-notice/1/)
- Observe (in the dev tools) the green Continue button no longer has an empty "id" tag.
> DLS-6149 Make the ID attribute on the "fit and proper" page optional

- app/views/components/back_link_notifications.scala.html
- public/amls.js
Make all back links work the same way - add a .click event to elements with a "link-back" class.
- Click on a "Back" link on the notifications/messages page to see it still works
> DLS-5803 Make all back links work the same way

- app/views/businessactivities/summary.scala.html
- app/views/businessdetails/summary.scala.html
- app/views/businessmatching/summary.scala.html
- app/views/msb/summary.scala.html
- app/views/renewal/summary.scala.html
- app/views/supervision/summary.scala.html
- app/views/tcsp/summary.scala.html
- app/views/tradingpremises/what_you_need.scala.html
Correct lists and fix duplicate IDs.
Some IDs weren't used anywhere, so got removed.
Others - I removed one of the two duplicated IDs, as it was used in tests, but it didn't matter which of the two links was clicked from acceptance tests perspective.
View the page and run Microsoft Accessibility check.
I've extracted the list of duplicated fields from Jenkins (link in the comment in the ticket).
1.	supervisionanotherbody-edit-name
2.	supervisionpenalised-edit
3.	anothertcspsupervision-edit
4.	msbwhichcurrencies-edit
5.	businessdetailsregisteredvat-edit
6.	edit-psr-number
7.	involvedinother-edit
8.	businessfranchise-edit
9.	howrecordskept-edit
> DLS-5804 Correct lists and fix duplicate IDs

- build.sbt
- conf/application-json-logger.xml
- conf/application.conf
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
**required:**
- bootstrap-play : 5.24.0 (any later seems to cause errors)
- sbt-plugin : 2.8.18
**additional:**
- play-partials : 8.3.0-play-28
- json-encryption : 5.1.0-play-28
- domain : 8.1.0-play-28
- play-ui : 9.11.0-play-28
- govuk-template : 5.78.0-play-28
- play-frontend-hmrc : 3.34.0-play-28
> [DLS-5490] - Play 2.8.16 upgrade for amls-frontend

- app/views/renewal/involved_in_other.scala.html
using safer mkString rather than head of list which could be empty & crash the page
> DDCYLS-2462

- app/models/responsiblepeople/ResponsiblePerson.scala
- app/models/tradingpremises/TradingPremises.scala
- app/views/components/TaskRowWithUpdateComponent.scala.html
- test/models/tradingpremises/TradingPremisesSpec.scala
- test/views/components/TaskRowWithUpdateComponentSpec.scala
This should only affect trading premises and responsible people rows as these are the sections which can have multiple sets of data, and therefore had the bugs. I added a new unit test spec for the recent view logic that was also updated here.
This is to address items on rows 22 and 23 of the bug bash spreadsheet.
> DDCYLS-4095 Fix to status tag logic for TP/RP

- app/utils/businessdetails/CheckYourAnswersHelper.scala
- app/views/DateOfChangeView.scala.html
- app/views/bankdetails/BankAccountNameView.scala.html
- app/views/bankdetails/BankAccountUKView.scala.html
- app/views/businessactivities/BusinessEmployeesAMLSSupervisionView.scala.html
- app/views/businessactivities/BusinessEmployeesCountView.scala.html
- app/views/businessdetails/ActivityStartDateView.scala.html
- app/views/hvd/CashPaymentFirstDateView.scala.html
- app/views/msb/CurrencyExchangesInNext12MonthsView.scala.html
- app/views/msb/FxTransactionInNext12MonthsView.scala.html
- app/views/msb/TransactionsInNext12MonthsView.scala.html
- app/views/renewal/CETransactionsInLast12MonthsView.scala.html
- app/views/renewal/FXTransactionsInLast12MonthsView.scala.html
- app/views/renewal/TransactionsInLast12MonthsView.scala.html
- app/views/responsiblepeople/DateOfBirthView.scala.html
- app/views/responsiblepeople/LegalNameChangeDateView.scala.html
- app/views/responsiblepeople/PositionWithinBusinessStartDateView.scala.html
- app/views/responsiblepeople/RemoveResponsiblePersonView.scala.html
- app/views/responsiblepeople/address/NewHomeDateOfChangeView.scala.html
- app/views/supervision/SupervisionEndReasonsView.scala.html
- app/views/supervision/SupervisionEndView.scala.html
- app/views/supervision/SupervisionStartView.scala.html
- app/views/tradingpremises/ActivityStartDateView.scala.html
- app/views/tradingpremises/AgentCompanyDetailsView.scala.html
- app/views/tradingpremises/AgentNameView.scala.html
- app/views/tradingpremises/AgentPartnershipView.scala.html
- app/views/tradingpremises/RemoveTradingPremisesView.scala.html
- test/utils/businessdetails/CheckYourAnswersHelperSpec.scala
- Attribute “pattern” not allowed on element “div” at this point --- removed
- Bad value “numeric” for attribute “type” on element “input” --- changed this to inputmode = “numeric”
- Duplicate ID “businessdetailsregform-edit” --- updated one of the IDs
- Form element does not have an implicit (wrapped) label --- added labels to multiple forms that didn’t have them
> DDCYLS-4035 Made various a11y fixes following assets upgrade

- app/controllers/tradingpremises/TradingPremisesAddController.scala
- app/models/tradingpremises/TradingPremises.scala
- app/services/TradingPremisesService.scala
- app/utils/RepeatingSection.scala
- test/controllers/tradingpremises/TradingPremisesAddControllerSpec.scala
- test/generators/tradingpremises/TradingPremisesGenerator.scala
- test/models/tradingpremises/TradingPremisesSpec.scala
- test/services/businessmatching/TradingPremisesServiceSpec.scala
Added addTradingPremisesFunction in TradingPremisesService that doesn't allow empty trading premises to be added to the database.
Added notEmpty function in TradingPremises that determines whether a trading premises is empty or not
TradingPremisesAddController now uses the service rather than RepeatingSection to add a trading premises
Added tests for the above.
> DDCYLS-3059

- app/views/declaration/DeclareView.scala.html
- app/views/deregister/DeregistrationReasonView.scala.html
- app/views/withdrawal/WithdrawalReasonView.scala.html
- public/submitButtonDisable.js
- test/views/declaration/DeclareViewSpec.scala
- test/views/deregister/DeregistrationReasonViewSpec.scala
- test/views/withdrawal/WithdrawalReasonViewSpec.scala
The attribute is now added to the form instead of the button, and the JS is triggered by the form's submit event.
> DDCYLS-4184 Tweak to disable button JS event handler

- app/controllers/businessactivities/InvolvedInOtherController.scala
- app/controllers/renewal/InvolvedInOtherController.scala
- app/controllers/responsiblepeople/ExperienceTrainingController.scala
- app/controllers/responsiblepeople/TrainingController.scala
- app/controllers/supervision/PenalisedByProfessionalController.scala
- app/controllers/supervision/SupervisionEndReasonsController.scala
- app/utils/CharacterCountParser.scala
- app/views/businessactivities/InvolvedInOtherNameView.scala.html
- app/views/renewal/InvolvedInOtherView.scala.html
- app/views/responsiblepeople/ExperienceTrainingView.scala.html
- app/views/responsiblepeople/TrainingView.scala.html
- conf/application.conf
- test/utils/CharacterCountParserSpec.scala
Check Jira story for notes regarding this fix.
Other misc changes:
- `govuk-label` class removed in a few places due to it being duplicated in the HTML (this is the default class you inherit for free when using Label component)
- Old assets config removed
- Auditing disabled locally to reduce spam logs, `traceRequests` removed to address platops comment
> DDCYLS-4212 Strip special char for character count component fix

- app/views/Layout.scala.html
- app/views/components/Stylesheets.scala.html
- project/AppDependencies.scala
- project/plugins.sbt
- test/views/businessmatching/CheckCompanyIsNotRegisteredViewSpec.scala
The test that was updated was because the GovukWarningText component now has some hidden text for screen readers that says "Warning". I've looked at the page to confirm behaviour (route = `/anti-money-laundering/business-matching/check-company-is-not-registered`)
> Upgrade play-frontend-hmrc

- app/services/cache/CacheOps.scala
- app/services/cache/MongoCacheClient.scala
- build.sbt
- conf/application.conf
- it/connectors/cache/DataCacheConnectorISpec.scala
- it/helpers/IntegrationBaseSpec.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/connectors/GovernmentGatewayConnectorSpec.scala
- test/services/cache/MongoCacheClientSpec.scala
- test/utils/AmlsSpec.scala
Please also merge this build-jobs PR to enable IT tests running: https://github.com/hmrc/build-jobs/pull/17003
Rolled back bootstrap, http-caching and the related config and crypto changes, whilst allowing us to stay on Scala 2.13. I've covered up a few gaps in tests but this is by no means exhaustive. There could be many more IT tests and the one I added was simply to add a bit of groundwork, but ultimately the scope of this ticket could be endless if trying to cover everything.
The issue on main can be reproduced by enabling encryption and going into the renewal journey. Switching on encryption locally as dicussed can also give us another barrier at the acceptance test stage to catch issues.
Also removed the silencer plugin as it is obselete in later Scala versions
> DDCYLS-2428 Rollback bootstrap & http-caching, enable encryption

- app/forms/mappings/Constraints.scala
- test/forms/renewal/CETransactionsInLast12MonthsFormProviderSpec.scala
- test/forms/renewal/FXTransactionsInLast12MonthsFormProviderSpec.scala
- test/forms/renewal/TransactionsInLast12MonthsFormProviderSpec.scala
The regex can stay as digits only because the forms strip out spaces/commas prior to the regex check
> DDCYLS-5484 Reverted regex for transaction inputs

- app/controllers/BacsConfirmationController.scala
- app/controllers/testonly/TestOnlyController.scala
- app/views/confirmation/ConfirmationBacsView.scala.html
- conf/messages
- test/controllers/BacsConfirmationControllerSpec.scala
As part of the AMLS registration and renewal journeys, the shared bacs confirmation screen now differentiates between the journey, displaying a new panel heading and text for the link to return to the dashboard.
> DDCYLS-5562 - differentiate between registration and renewal journey for bacs confirmation screen

- app/views/renewal/CustomersOutsideUKView.scala.html
- app/views/renewal/MostTransactionsView.scala.html
- app/views/renewal/SendLargestAmountsOfMoneyView.scala.html
- app/views/renewal/WhichCurrenciesView.scala.html
- app/views/responsiblepeople/CountryOfBirthView.scala.html
- app/views/responsiblepeople/NationalityView.scala.html
- public/autocomplete-polyfill.css
- public/autocomplete-polyfill.js
- Applied the autocomplete polyfill to resolve an accessibility issue where error messages were not correctly announced to screen readers.
- Ensured that when an error occurs, the aria-describedby attribute points to both the error message and any associated hint for the visible input element
> DDCYLS-4866 - Autocomplete fields missing link to error message 
