public/amls.js
Progressive reveal button actions are now announced to screen readers.
=> a11y fix for progressive reveal

app/connectors/GovernmentGatewayConnector.scala, app/controllers/SubmissionController.scala, app/controllers/testonly/TestOnlyController.scala, app/exceptions/InvalidEnrolmentCredentialsException.scala, app/views/duplicate_submission.scala.html, app/views/submission/duplicate_enrolment.scala.html, app/views/submission/wrong_credential_type.scala.html, conf/messages, conf/testOnlyDoNotUseInAppConf.routes, test/controllers/SubmissionControllerSpec.scala, test/views/DuplicateSubmissionViewSpec.scala, test/views/submission/duplicate_enrolmentSpec.scala, test/views/submission/wrong_credential_typeSpec.scala
This contains the work for the ‘credential has the wrong type of role’ error
=> AMLS-2915: Government Gateway error pages

app/connectors/AmlsConnector.scala, app/controllers/StatusController.scala, app/models/registrationdetails/RegistrationDetails.scala, test/connectors/AmlsConnectorSpec.scala, test/controllers/StatusControllerSpec.scala, test/controllers/StatusControllerWithoutAmendmentsSpec.scala, test/controllers/StatusControllerWithoutNotificationsSpec.scala, test/models/registrationdetails/RegistrationDetailsSpec.scala
Updated the frontend to make use of the new AMLS endpoint in order to retrieve the company name.
=> AMLS-2950: Updating Company Name

app/audit/BacsPaymentEvent.scala, app/controllers/payments/TypeOfBankController.scala, test/controllers/payments/TypeOfBankControllerSpec.scala
TxM have requested:
* AMLS ref number
* Payment reference
* Amount
=> Added more detail into the bacs auditing

project/FrontendBuild.scala
..because it was out of date on the Tax Catalogue
=> Upgraded frontend-bootstrap library version

test/models/bankdetails/BankAccountSpec.scala, test/models/bankdetails/BankDetailsSpec.scala
Ongoing refactoring of BankDetails tests. Account tests have been moved from the top-level model to BankAccountSpec and a trait created to hold models and associated JSON. This being done in preparation of backwards-compatibility serialisation/deserialisation tests
=> Refactoring bankDetails tests

app/connectors/AuthConnector.scala, app/connectors/EnrolmentStoreConnector.scala, app/models/bankdetails/BankDetails.scala, test/connectors/AuthConnectorSpec.scala, test/models/bankdetails/BankDetailsSpec.scala
Coverage has been turned off for Enrolment placeholder classes, until they become used later.
=> Various tests to improve coverage

app/controllers/supervision/WhichProfessionalBodyController.scala, app/models/supervision/Supervision.scala, conf/app.routes, test/controllers/supervision/WhichProfessionalBodyControllerSpec.scala, test/models/supervision/SupervisionSpec.scala
Setup edit, save of data,  complete testing on JSON
=> Amls 3020: Page split: Is your business a member of a professional body

app/controllers/responsiblepeople/AdditionalAddressController.scala, app/controllers/responsiblepeople/AdditionalExtraAddressController.scala, app/controllers/responsiblepeople/CurrentAddressController.scala, app/controllers/responsiblepeople/NationalityController.scala, app/controllers/responsiblepeople/NewHomeAddressController.scala, app/views/responsiblepeople/additional_address.scala.html, app/views/responsiblepeople/additional_extra_address.scala.html, app/views/responsiblepeople/current_address.scala.html, app/views/responsiblepeople/nationality.scala.html, app/views/responsiblepeople/new_home_address.scala.html, test/controllers/responsiblepeople/AdditionalAddressControllerSpec.scala, test/controllers/responsiblepeople/AdditionalExtraAddressControllerSpec.scala, test/controllers/responsiblepeople/CurrentAddressControllerSpec.scala, test/controllers/responsiblepeople/NationalityControllerSpec.scala, test/controllers/responsiblepeople/NewHomeAddressControllerSpec.scala, test/views/responsiblepeople/additional_addressSpec.scala, test/views/responsiblepeople/additional_extra_addressSpec.scala, test/views/responsiblepeople/current_addressSpec.scala, test/views/responsiblepeople/nationalitySpec.scala, test/views/responsiblepeople/new_home_addressSpec.scala
This code has generated a live issue, and so has been reverted out of master until the issue has been resolved.
=> Reverted AMLS-2659

app/controllers/responsiblepeople/AdditionalAddressController.scala, app/controllers/responsiblepeople/AdditionalExtraAddressController.scala, app/controllers/responsiblepeople/CurrentAddressController.scala, app/controllers/responsiblepeople/NationalityController.scala, app/controllers/responsiblepeople/NewHomeAddressController.scala, app/views/responsiblepeople/additional_address.scala.html, app/views/responsiblepeople/additional_extra_address.scala.html, app/views/responsiblepeople/current_address.scala.html, app/views/responsiblepeople/nationality.scala.html, app/views/responsiblepeople/new_home_address.scala.html, test/controllers/responsiblepeople/AdditionalAddressControllerSpec.scala, test/controllers/responsiblepeople/AdditionalExtraAddressControllerSpec.scala, test/controllers/responsiblepeople/CurrentAddressControllerSpec.scala, test/controllers/responsiblepeople/NationalityControllerSpec.scala, test/controllers/responsiblepeople/NewHomeAddressControllerSpec.scala, test/views/responsiblepeople/additional_addressSpec.scala, test/views/responsiblepeople/additional_extra_addressSpec.scala, test/views/responsiblepeople/current_addressSpec.scala, test/views/responsiblepeople/nationalitySpec.scala, test/views/responsiblepeople/new_home_addressSpec.scala
Previously reported live issue has been resolved, so this can come back in.
=> AMLS-2659: Reverted the reverted country lookup code from master

app/views/include/status/rightpanel_submissiondecisionexpired.scala.html, test/views/status/status_expiredSpec.scala
This reimplements the reverted commit 797dfca77018ac6f2d7559d59a54e428a6455d2c.
=> AMLS-2990: Allow re-register after renewal window expiry

app/config/ApplicationConfig.scala, app/controllers/StatusController.scala, app/controllers/businessmatching/SummaryController.scala, app/controllers/deregister/DeRegisterApplicationController.scala, app/views/deregister/deregister_application.scala.html, app/views/status/status_supervised.scala.html, conf/application.conf, test/controllers/businessmatching/SummaryControllerSpec.scala, test/controllers/deregister/DeRegisterApplicationControllerSpec.scala, test/views/deregister/deregister_applicationSpec.scala, test/views/status/status_supervisedSpec.scala
* Also fixes previous broken build
=> AMLS-3715: Removing businessMatchingVariationToggle

app/views/businessmatching/updateservice/remove/remove_activities.scala.html
The button was placed outside of the main form element.
=> AMLS-3784: Fixed issue with button not working

app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala, app/services/flowmanagement/pagerouters/removeflow/RemoveBusinessTypesSummaryPageRouter.scala, conf/messages, test/controllers/businessmatching/updateservice/RemoveBusinessTypeHelperSpec.scala, test/services/flowmanagement/flowrouters/RemoveBusinessTypeRouterSpec.scala
Also includes updated content for this page.
=> AMLS-3847: Showing the 'we need you to update..' page if trading premises are incomplete

app/views/businessmatching/summary.scala.html, app/views/businessmatching/updateservice/add/update_services_summary.scala.html
Business Matching Checkyouranswers - edit-business-activities => businessactivities-edit
Business Matching Checkyouranswers - edit-msb-services => msbservices-edit
Updateservice add Checkyouranswers - edit-msg-services => msbservices-edit
Updateservice add Checkyouranswers - WhatDoYouDoHere => whatdoyoudohere
=> Renamed some checkyouranswers ids to align with the existing ones.

app/controllers/tcsp/AnotherTCSPSupervisionController.scala, app/controllers/tcsp/ProvidedServicesController.scala, app/controllers/tcsp/ServicesOfAnotherTCSPController.scala, app/controllers/tcsp/SummaryController.scala, app/controllers/tcsp/TcspTypesController.scala, app/controllers/tcsp/WhatYouNeedController.scala, conf/app.routes, test/controllers/tcsp/AnotherTCSPSupervisionControllerSpec.scala, test/controllers/tcsp/ProvidedServicesControllerSpec.scala, test/controllers/tcsp/ServicesOfAnotherTCSPControllerSpec.scala, test/controllers/tcsp/SummaryControllerSpec.scala, test/controllers/tcsp/TcspTypesControllerSpec.scala, test/controllers/tcsp/WhatYouNeedControllerSpec.scala
All controlers and Specs and optimised imports
=> refactor-for-di | controllers.tcsp

app/controllers/businessmatching/MsbSubSectorsController.scala, app/controllers/businessmatching/RegisterServicesController.scala, app/views/businessmatching/services.scala.html, app/views/businessmatching/summary.scala.html, conf/businessMatching.routes, test/controllers/businessmatching/MsbSubSectorsControllerSpec.scala, test/controllers/businessmatching/RegisterServicesControllerSpec.scala, test/views/businessmatching/summarySpec.scala
Also changed the name from `ServicesController` to `MsbSubSectorsController`
=> AMLS-3802 Refactored MsbSubSectorsController for DI

app/views/bankdetails/your_bank_accounts.scala.html, conf/messages, test/views/bankdetails/your_bank_accountsSpec.scala
* Moved some of the common stuff into reusable Twirl functions
* Restored a couple of message keys that had been blatted out from a previous poor merge
=> AMLS-3892 Refactored 'Your bank accounts' view

app/controllers/bankdetails/RemoveBankDetailsController.scala, test/controllers/bankdetails/RemoveBankDetailsControllerSpec.scala
=> AMLS-3926 | Redirected RemoveBankDetails - YourBankAccounts

app/controllers/bankdetails/BankAccountIsUKController.scala, app/controllers/bankdetails/BankAccountNameController.scala, app/controllers/bankdetails/BankAccountTypeController.scala, app/controllers/bankdetails/BankDetailsController.scala, app/controllers/bankdetails/RemoveBankDetailsController.scala, app/controllers/bankdetails/SummaryController.scala, app/controllers/bankdetails/YourBankAccountsController.scala, app/models/bankdetails/BankDetails.scala, app/utils/ControllerHelper.scala, conf/bankDetails.routes, test/controllers/bankdetails/BankAccountIsUKControllerSpec.scala, test/controllers/bankdetails/BankAccountNameControllerSpec.scala, test/controllers/bankdetails/BankAccountTypeControllerSpec.scala, test/controllers/bankdetails/RemoveBankDetailsControllerSpec.scala, test/controllers/bankdetails/SummaryControllerSpec.scala
=> AMLS-3927 Edit flows from CYA page

app/views/bankdetails/your_bank_accounts.scala.html
Also changed the headers from `h3` to `h2`
=> AMLS-3917 Corrected display of Option type on 'bank accounts' view

app/controllers/bankdetails/BankAccountTypeController.scala, app/views/bankdetails/bank_account_types.scala.html, conf/bankDetails.routes, test/views/bankdetails/bank_account_typeSpec.scala
and added / to some bankdetails routes to stop security path traversal errors
=> Removed the count parameter from bankaccounttypecontroller

app/views/include/forms2/country.scala.html, app/views/include/forms2/currency.scala.html, app/views/include/forms2/inlineRadioGroup.scala.html, app/views/include/forms2/labelWithInput.scala.html, app/views/include/forms2/panel.scala.html, app/views/include/forms2/radioGroup.scala.html, app/views/include/forms2/rpInput.scala.html
NOTE: 
Not specific to Renewal process. 
The tags were added where they were missing given the id 'error-notification'
=> Add element id to error-notification elements for GA

app/audit/ESEnrolEvent.scala, app/connectors/EnrolmentStoreConnector.scala, app/models/enrolment/TaxEnrolment.scala, app/services/AuthEnrolmentsService.scala, test/connectors/EnrolmentStoreConnectorSpec.scala, test/models/enrolment/TaxEnrolmentSpec.scala, test/services/AuthEnrolmentsServiceSpec.scala
Change Enrolment Model to TaxEnrolement
Note: Current issue with acceptance test suite failing prevents automation sign off on this PR.
=> Amls 4088 - Change Enrolment Model to TaxEnrolement

app/connectors/AuthenticatorConnector.scala, app/controllers/ConfirmationController.scala, app/controllers/StatusController.scala, app/controllers/SubmissionController.scala, app/filters/ConfirmationFilter.scala, test/connectors/AuthenticatorConnectorSpec.scala, test/controllers/ConfirmationControllerSpec.scala, test/controllers/StatusControllerSpec.scala, test/controllers/SubmissionControllerSpec.scala, test/filters/ConfirmationFilterSpec.scala
Reverts hmrc/amls-frontend#757
=> Revert "Amls 4090 - Remove Refresh Profile and AuthenicatorConnector"

conf/application.conf
Enabled mongo in the local application config
=> Enabled mongo in application config

app/controllers/renewal/FXTransactionsInLast12MonthsController.scala, app/models/renewal/FXTransactionsInLast12Months.scala, app/models/renewal/Renewal.scala, app/services/RenewalService.scala, app/views/renewal/fx_transaction_in_last_12_months.scala.html, conf/messages, conf/renewal.routes, test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala, test/controllers/renewal/SummaryControllerSpec.scala, test/models/renewal/FXTransactionsInLast12MonthsSpec.scala, test/services/LandingServiceSpec.scala, test/services/RenewalServiceSpec.scala, test/views/renewal/fx_transactions_in_last_12_monthsSpec.scala, test/views/renewal/summarySpec.scala
* Adds view, controller, model for FX renewals
* Page not part of flow
* Set automatically to None in the data model
Work in place to implement FX in renewal flow, following on from previous work to add it to Pre-app and MSB flow.
N/A
* Unit tests
* Manual functional tests
=> AMLS-4026 | AMLS-4027 | Create new screen "How many foreign exchange transactions did you make in the last 12 months"

app/views/satisfaction_survey.scala.html, conf/messages, public/amls.css, test/views/satisfaction_surveySpec.scala
- Updated hint test
- Left justified word count
- Created unit tests
as above
Unit test
=> AMLS-4193 | Added hint text, unit tests and moved word count to left

app/views/include/main.scala.html, app/views/include/main2.scala.html
Added Cache Buster to CSS
Updated main and main2 templates
Ran unit tests, inspected screen source when running the system
=> AMLS-4193 | Added Cache Buster to CSS

app/views/renewal/ce_transactions_in_last_12_months.scala.html, app/views/renewal/fx_transaction_in_last_12_months.scala.html, app/views/renewal/summary.scala.html, conf/messages, test/controllers/renewal/CETransactionsInLast12MonthsControllerSpec.scala, test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala, test/controllers/renewal/SummaryControllerSpec.scala, test/views/renewal/ce_transactions_in_last_12_monthsSpec.scala, test/views/renewal/fx_transactions_in_last_12_monthsSpec.scala, test/views/renewal/summarySpec.scala
Added FX to the CYA renewals page
Added FX to the summary view and refactored unit tests to include this
=> AMLS-4096 | Added FX to CYA page - Refactored Unit tests

app/models/renewal/Conversions.scala, test/models/renewal/ConversionsSpec.scala
Ensure FX question data is applied to submission request
* Adds conversion of renewal question for FX to be applied to MSB section FX question in renewal subscription request
N/A
*Unit tests
=> AMLS-4026 | AMLS-4194 | Ensure FX question data is applied to submission request

app/controllers/renewal/FXTransactionsInLast12MonthsController.scala, app/controllers/renewal/MostTransactionsController.scala, app/controllers/renewal/SendMoneyToOtherCountryController.scala, app/controllers/renewal/TotalThroughputController.scala, app/controllers/renewal/WhichCurrenciesController.scala, test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala, test/controllers/renewal/MostTransactionsControllerSpec.scala, test/controllers/renewal/SendMoneyToOtherCountryControllerSpec.scala, test/controllers/renewal/TotalThroughputControllerSpec.scala, test/controllers/renewal/WhichCurrenciesControllerSpec.scala
Adding new screen into the renewal flow as specified in JIRA ticket.
* Slight refactor to current routing in Renewal
* Implements flow as described in ticket Scenarios 2,4,5
* Implements flow as described in ticket Scenarios 3
* Implements flow as described in ticket Scenarios 1
Is dependent on all other AMLS-4026 PRs - should be last one to be merged before QA testing
* Unit tests
=> AMLS-4026 | AMLS-4191 | Add new screen "How many foreign exchange..." to renewal flow as specified in Scenarios 1-5

conf/messages
Fixed content bug.
No.
* Unit tests
* Manual tests
* Acceptance tests
=> AMLS-4265 Bug fix - content errors.

app/controllers/responsiblepeople/RemoveResponsiblePersonController.scala
=> AMLS-4266 | BUG - With user XAML00000567894, submitting after adding and removing an incomplete responsible person causes scheme error

upversion-templates.sh
=> AMLS-3873 | Adds echo statements to upversioning script

app/views/responsiblepeople/detailed_answers.scala.html
=> added id onto rp check your answers

app/controllers/AmlsController.scala, project/MicroService.scala, project/plugins.sbt
=> Added required config for new build process

app/views/include/submit_application.scala.html, app/views/registrationprogress/registration_progress.scala.html
Manual testing via developer tools
=> Added ID onto progress page continue button

app/controllers/renewal/RenewalProgressController.scala, app/services/RenewalService.scala, app/views/renewal/application_submit.scala.html, app/views/renewal/renewal_progress.scala.html, test/services/RenewalServiceSpec.scala, test/views/renewal/renewal_progressSpec.scala
Fixes renewal service canSubmit
Unit tests
Manual testing
=> AMLS-3659 | submitting an incomplete Renewal application

app/controllers/declaration/WhoIsRegisteringController.scala
=> AMLS-4380 | Chains redirect on WhoIsRegisteringController

app/controllers/responsiblepeople/ApprovalCheckController.scala, app/views/responsiblepeople/approval_check.scala.html, conf/messages, conf/responsiblePeople.routes, test/controllers/responsiblepeople/ApprovalCheckControllerSpec.scala, test/views/responsiblepeople/approval_checkSpec.scala
Add new view and controller for approval check question. 
https://github.com/hmrc/amls-frontend/pull/811
Unit Testing
=> Amls 4334 from amls 3754 v2

app/controllers/responsiblepeople/FitAndProperController.scala, app/views/responsiblepeople/approval_check.scala.html, conf/application.conf, conf/messages, test/controllers/responsiblepeople/FitAndProperControllerSpec.scala, test/views/responsiblepeople/approval_checkSpec.scala
Implement flow for approval check and ensure both fit and proper and approval values get set correctly/ 
N/A
Unit tests and manual testing given the scenarios. Regression automation also run.
=> Amls 4335 implement flow

test/controllers/responsiblepeople/ConfirmAddressControllerSpec.scala, test/controllers/responsiblepeople/FitAndProperControllerSpec.scala
refactored some of the multi code duplication
=> Amls 3754 tests refactor

app/views/responsiblepeople/detailed_answers.scala.html
=> Add ids to fit and proper and approval edit links

app/utils/RepeatingSection.scala
PR to address:
https://jira.tools.tax.service.gov.uk/browse/AMLS-4423
Fix for mongo encryption issue when fetching data for update. 
N/A
Unit tests run and manual testing adding a responsible person. Verified issue locally with mongo encryption switched on. Then verified fix resolved the issue.
=> Fix to mongo encryption issue in staging

conf/application.conf
=> toggle update to test in staging

app/views/responsiblepeople/detailed_answers.scala.html
Just added an ID to an edit link on RP CYA page - Hope I've done it right!
Manual testing on front end code
=> added id to UK Passport Question on CYA

app/controllers/ConfirmationController.scala
=> Add logging around fees

app/controllers/ConfirmationController.scala, app/services/AuthEnrolmentsService.scala, app/services/FeeResponseService.scala, conf/application.conf
Add logging for dev and staging issue...
N/A
Local testing and run unit tests
=> Add enrolment logging

app/views/status/status_deregistered.scala.html, app/views/status/status_expired.scala.html, app/views/status/status_incomplete.scala.html, app/views/status/status_not_submitted.scala.html, app/views/status/status_rejected.scala.html, app/views/status/status_renewal_incomplete.scala.html, app/views/status/status_renewal_not_submitted.scala.html, app/views/status/status_renewal_submitted.scala.html, app/views/status/status_revoked.scala.html, app/views/status/status_submitted.scala.html, app/views/status/status_withdrawn.scala.html
=> added IDs to status

app/connectors/TaxEnrolmentsConnector.scala, conf/application.conf, test/connectors/TaxEnrolmentsConnectorSpec.scala
Fix issue with no fees for new subscriptions in development and staging. Issue was PUT and GET for tax enrolments talking to different services. 
N/A
Unit testing and local.
=> Fix dev and staging issue with fees

app/views/aboutthebusiness/corporation_tax_registered.scala.html, app/views/aboutthebusiness/previously_registered.scala.html, app/views/aboutthebusiness/vat_registered.scala.html, app/views/bankdetails/bank_account_is_uk.scala.html, app/views/businessmatching/company_registration_number.scala.html, app/views/businessmatching/psr_number.scala.html, app/views/businessmatching/updateservice/add/business_applied_for_psr_number.scala.html
Type of input fields changed to numbers, to display correct keyboard when using mobile phones/tablets (tel - type is deprecated).
Removed few commented lines of code.
none
- run of all unit tests
- manual tests
=> AMLS-4489 | Accessibility issue fix.

app/views/include/forms2/country.scala.html, app/views/include/forms2/currency.scala.html, app/views/include/forms2/inlineRadioGroup.scala.html, app/views/include/forms2/labelWithInput.scala.html, app/views/include/forms2/panel.scala.html, app/views/include/forms2/radioGroup.scala.html, app/views/include/forms2/rpInput.scala.html
Fix for Google Analytics name fields for MSB (and other journeys).
none
- run of unit tests
- manual check of generated website code
- manual with GA testing possible only in QA
=> AMLS-3395 | Fixed not correctly referenced field names of GA attributes.

app/models/responsiblepeople/ResponsiblePerson.scala, test/models/responsiblepeople/ResponsiblePersonSpec.scala
For MSB TCSP sectors set approval equal to fit and proper
N/A
Unit test and Acceptance Tets
=> For MSB TCSP sectors set approval equal to fit and proper

app/models/FormTypes.scala, app/models/aboutthebusiness/ActivityStartDate.scala, app/models/tradingpremises/ActivityStartDate.scala, conf/messages, test/models/aboutthebusiness/ActivityStartDateSpec.scala, test/models/hvd/CashPaymentSpec.scala, test/models/tradingpremises/ActivityStartDateSpec.scala
made the UI apply min allowed DoB to enforce valid data passed to ETMP
Jira Ticket:
https://jira.tools.tax.service.gov.uk/browse/AMLS-4523
=> added min allowed DoB check before ETMP blow up

app/views/confirmation/confirmation_new.scala.html, test/views/confirmation/SubmitRegistrationConfirmationViewSpec.scala
Submit registration - Application fee and reference - change button to continue
=> Amls 3154 Application fee and reference button change

conf/messages
=> AMLS-3937 | Changed landing page content and button text

app/views/renewal/amls_turnover.scala.html
PR to change the legend text.
none
- manual testing
=> AMLS-3886 | Changed Legend on Renewal Turnover page

conf/messages
update to generic comm contents
=> AMLS-4270 | generic comm content change

app/services/ConfirmationService.scala, app/typeclasses/confirmation/ResponsiblePeopleRows.scala, app/utils/ActivitiesHelper.scala, test/services/ConfirmationServiceSpec.scala, test/services/ConfirmationServiceSpecWithPhase2Changes.scala, test/typeclasses/confirmation/ResponsiblePeopleRowsPhase2Spec.scala
Fix to fee breakdown table for appropriate business types given answers to F&P and Approval. 
N/A
Unit and Local Testing
=> Fix fee breakdown

app/controllers/LandingController.scala
=> AMLS-4558 | added log debug to place suspected to fail the expected path

app/services/LandingService.scala
added logger to LandingService
=> AMLS-4558-add-log2 | added more logs to LandingService

app/views/businessmatching/cannot_continue_with_the_application.scala.html, app/views/businessmatching/company_registration_number.scala.html, app/views/businessmatching/psr_number.scala.html, app/views/businessmatching/register_services.scala.html, app/views/businessmatching/services.scala.html, app/views/businessmatching/type_of_business.scala.html, test/views/businessmatching/PsrNumberViewSpec.scala, test/views/businessmatching/company_registration_numberSpec.scala, test/views/businessmatching/register_servicesSpec.scala, test/views/businessmatching/servicesSpec.scala, test/views/businessmatching/type_of_businessSpec.scala
In this PR there are changes to pre-application pages: added back link
none
- manual
- unit tests
=> Amls 4540  - back links: pre-application

public/amls.css
Add small margin to bottom of back link
N/A
Manual visual checks
=> Add small margin to bottom of back link

app/controllers/asp/SummaryController.scala, app/controllers/estateagentbusiness/SummaryController.scala, app/controllers/hvd/SummaryController.scala, app/controllers/msb/SummaryController.scala, app/controllers/tcsp/SummaryController.scala, app/services/businessmatching/ServiceFlow.scala, test/controllers/asp/SummaryControllerSpec.scala, test/controllers/estateagentbusiness/SummaryControllerSpec.scala, test/controllers/hvd/SummaryControllerSpec.scala, test/controllers/msb/SummaryControllerSpec.scala, test/controllers/tcsp/SummaryControllerSpec.scala, test/services/businessmatching/updateservice/ServiceFlowSpec.scala, test/utils/ServiceFlowMocks.scala
In this PR there is removed redundant and deprecated code from businessmatching/serviceflow
Removed code was not hit by by any function therefore removal has no impact on existing functionalities.
none
- regression
- manually tests
=> Amls 4579 - removed redundant code from service flow

app/views/responsiblepeople/legal_name.scala.html
Fix to bug in visually hidden text.
none
- manual
=> AMLS-4547 | BUG FIX: Visually hidden text read: Has curly bracket zero curly bracket - no more

app/views/asp/other_business_tax_matters.scala.html, app/views/asp/services_of_business.scala.html, app/views/asp/what_you_need.scala.html, app/views/supervision/another_body.scala.html, app/views/supervision/member_of_professional_body.scala.html, app/views/supervision/penalised_by_professional.scala.html, app/views/supervision/what_you_need.scala.html, app/views/supervision/which_professional_body.scala.html, test/views/asp/other_business_tax_mattersSpec.scala, test/views/asp/services_of_businessSpec.scala, test/views/asp/what_you_needSpec.scala, test/views/supervision/another_bodySpec.scala, test/views/supervision/member_of_professional_bodySpec.scala, test/views/supervision/penalised_by_professionalSpec.scala, test/views/supervision/what_you_needSpec.scala, test/views/supervision/which_professional_bodySpec.scala
=> Amls 4543 - backlink added to Supervision and ASP sections

conf/messages
=> AMLS-4583 | Changed action required message

app/views/components/back_link.scala.html, app/views/include/main.scala.html, app/views/include/main2.scala.html, app/views/include/notifications_your_messages.scala.html, app/views/include/whatyouneed.scala.html, conf/messages
Moved .service-info above #content and wrapped in a .centered-content
=> AMLS-4609 | Moved .service-info out of #content

app/views/responsiblepeople/fit_and_proper.scala.html, conf/messages, test/views/responsiblepeople/fit_and_properSpec.scala
Updated text on Fit and Proper and approval pages. Removed redundant phase2 toggles on Fit and Proper page, and updated tests.
=> AMLS-4598 | Amend F&P and Approval content

app/config/ApplicationGlobal.scala, conf/application.conf
Add metrics to AMLS FE
https://github.com/hmrc/app-config-base/pull/1606
Unit tests run
=> Add config metrics

test/connectors/FeeConnectorSpec.scala
Fix failing spec in new build. 
N/A
Unit test
=> Fix new build fail in spec

app/controllers/bankdetails/BankAccountIsUKController.scala, app/controllers/bankdetails/BankAccountNameController.scala, app/controllers/bankdetails/BankAccountTypeController.scala, app/controllers/bankdetails/BankDetailsController.scala, app/controllers/bankdetails/RemoveBankDetailsController.scala, app/controllers/bankdetails/SummaryController.scala, app/controllers/bankdetails/YourBankAccountsController.scala, test/controllers/bankdetails/RemoveBankDetailsControllerSpec.scala, test/controllers/bankdetails/SummaryControllerSpec.scala, test/controllers/bankdetails/YourBankAccountsControllerSpec.scala
DI instead of class member data
=> Amls 4638 - bankdetails controllers DI refactor

app/views/tcsp/another_tcsp_supervision.scala.html, app/views/tcsp/provided_services.scala.html, app/views/tcsp/service_provider_types.scala.html, app/views/tcsp/services_of_another_tcsp.scala.html, app/views/tcsp/what_you_need.scala.html, test/views/tcsp/another_tcsp_supervisionSpec.scala, test/views/tcsp/provided_servicesSpec.scala, test/views/tcsp/service_provider_typesSpec.scala, test/views/tcsp/services_of_another_tcspSpec.scala, test/views/tcsp/what_you_needSpec.scala
=> Amls 4546 - back button for TCSP

app/views/renewal/business_turnover.scala.html, test/views/renewal/business_turnoverSpec.scala
AMLS-4676 | Added missing back link to 'How much net profit page' in renewal flow and updated unit tests
NONE
- Unit tests, manually
=> AMLS-4676 | Added missing back link to 'How much net profit page' in renewal flow and updated unit tests

app/views/declaration/add_person.scala.html, app/views/declaration/declare.scala.html, app/views/declaration/register_partners.scala.html, app/views/declaration/register_responsible_person.scala.html, app/views/declaration/select_business_nominated_officer.scala.html, app/views/declaration/who_is_registering_this_registration.scala.html, app/views/declaration/who_is_registering_this_renewal.scala.html, app/views/declaration/who_is_registering_this_update.scala.html, test/views/declaration/add_personSpec.scala, test/views/declaration/declaration_Spec.scala, test/views/declaration/register_partnersSpec.scala, test/views/declaration/register_responsible_personSpec.scala, test/views/declaration/select_business_nominated_officerSpec.scala, test/views/declaration/who_is_registering_this_registrationSpec.scala, test/views/declaration/who_is_registering_this_renewalSpec.scala, test/views/declaration/who_is_registering_this_updateSpec.scala
=> Amls 4548 - Submission flow back button

app/controllers/tradingpremises/MSBServicesController.scala, app/controllers/tradingpremises/RemoveAgentPremisesReasonsController.scala, app/controllers/tradingpremises/RemoveTradingPremisesController.scala, app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala, app/controllers/tradingpremises/WhereAreTradingPremisesController.scala, conf/tradingPremises.routes, test/controllers/tradingpremises/MSBServicesControllerSpec.scala, test/controllers/tradingpremises/RemoveAgentPremisesReasonsControllerSpec.scala, test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala, test/controllers/tradingpremises/WhatDoesYourBusinessDoControllerSpec.scala, test/controllers/tradingpremises/WhereAreTradingPremisesControllerSpec.scala
Trading Premises Controller DI conversion.
Acceptance test full suite, Passed.
Unit tests amended/added.
=> Amls 4640 - Trading Premises Controller DI conversion.

app/controllers/tradingpremises/AgentNameController.scala, test/controllers/tradingpremises/AgentNameControllerSpec.scala
Changed redirect field in date of change page for sole trader edit.
Unit tests
=> AMLS-4678 | Changed the date of change redirect field 

app/controllers/estateagentbusiness/PenalisedByProfessionalController.scala, app/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActController.scala, app/controllers/estateagentbusiness/ResidentialRedressSchemeController.scala, app/controllers/estateagentbusiness/ServicesDateOfChangeController.scala, app/controllers/estateagentbusiness/WhatYouNeedController.scala, conf/estateAgents.routes, test/controllers/estateagentbusiness/PenalisedByProfessionalControllerSpec.scala, test/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActControllerSpec.scala, test/controllers/estateagentbusiness/ResidentialRedressSchemeControllerSpec.scala, test/controllers/estateagentbusiness/ServicesDateOfChangeControllerSpec.scala, test/controllers/estateagentbusiness/WhatYouNeedControllerSpec.scala
Updated EAB controllers and routes with dependency injection, updated specs where necessary.
Passes spec tests and acceptance tests.
=> AMLS-4643 | Updated EAB controllers, specs and routes with DI

app/connectors/BusinessMatchingConnector.scala, app/controllers/aboutthebusiness/ActivityStartDateController.scala, app/controllers/aboutthebusiness/ConfirmRegisteredOfficeController.scala, app/controllers/aboutthebusiness/ContactingYouController.scala, app/controllers/aboutthebusiness/ContactingYouPhoneController.scala, app/controllers/aboutthebusiness/CorporationTaxRegisteredController.scala, app/controllers/aboutthebusiness/CorrespondenceAddressController.scala, app/controllers/aboutthebusiness/LettersAddressController.scala, app/controllers/aboutthebusiness/PreviouslyRegisteredController.scala, app/controllers/aboutthebusiness/RegisteredOfficeController.scala, app/controllers/aboutthebusiness/RegisteredOfficeDateOfChangeController.scala, app/controllers/aboutthebusiness/SummaryController.scala, app/controllers/aboutthebusiness/VATRegisteredController.scala, app/controllers/aboutthebusiness/WhatYouNeedController.scala, app/services/LandingService.scala, conf/aboutTheBusiness.routes, test/connectors/BusinessMatchingConnectorSpec.scala, test/controllers/aboutthebusiness/ActivityStartDateControllerSpec.scala, test/controllers/aboutthebusiness/ConfirmRegisteredOfficeControllerSpec.scala, test/controllers/aboutthebusiness/ContactingYouControllerSpec.scala, test/controllers/aboutthebusiness/ContactingYouPhoneControllerSpec.scala, test/controllers/aboutthebusiness/CorporationTaxRegisteredControllerSpec.scala, test/controllers/aboutthebusiness/CorrespondenceAddressControllerSpec.scala, test/controllers/aboutthebusiness/LettersAddressControllerSpec.scala, test/controllers/aboutthebusiness/PreviouslyRegisteredControllerSpec.scala, test/controllers/aboutthebusiness/RegisteredOfficeControllerSpec.scala, test/controllers/aboutthebusiness/RegisteredOfficeDateOfChangeControllerSpec.scala, test/controllers/aboutthebusiness/SummaryControllerSpec.scala, test/controllers/aboutthebusiness/VATRegisteredControllerSpec.scala, test/controllers/aboutthebusiness/WhatYouNeedControllerSpec.scala
Converting About the Business controllers to use Dependency Injection
BusinessMatchingConnector also had to be DI'd to enable the injection within one of the controllers
Full unit test amendment
Full acceptance test suite ran
=> Amls 4636 - AbouttheBusinessControllers DI conversion

app/views/payments/bank_details.scala.html, app/views/payments/type_of_bank.scala.html, app/views/payments/ways_to_pay.scala.html, test/views/payments/bank_detailsSpec.scala, test/views/payments/type_of_bankSpec.scala, test/views/payments/ways_to_paySpec.scala
BACS payment flow back button additions with unit tests
Unit tests
Manually
=> Amls 4682 - Payment flow back button

app/controllers/aboutthebusiness/RegisteredOfficeController.scala, app/controllers/renewal/CustomersOutsideUKController.scala, app/controllers/renewal/SendTheLargestAmountsOfMoneyController.scala, app/views/aboutthebusiness/registered_office.scala.html, app/views/renewal/customers_outside_uk.scala.html, app/views/renewal/send_largest_amounts_of_money.scala.html, public/amls.js, public/autocomplete/location-autocomplete-graph.json, test/controllers/aboutthebusiness/RegisteredOfficeControllerSpec.scala, test/controllers/renewal/SendTheLargestAmountsOfMoneyControllerSpec.scala, test/services/ProgressServiceSpec.scala, test/views/aboutthebusiness/registered_officeSpec.scala, test/views/renewal/customers_outside_ukSpec.scala, test/views/renewal/send_largest_amounts_of_moneySpec.scala
Replaced the remaining country fields with autocomplete fields
Spec tests and acceptance tests pass, checked by Mike.
=> AMLS 4679 | Country auto complete fields

app/models/notifications/NotificationDetails.scala, app/models/notifications/NotificationRow.scala, app/services/NotificationService.scala, app/utils/ContactTypeHelper.scala, app/views/notifications/your_messages.scala.html, conf/messages, test/models/notifications/NotificationDetailsSpec.scala, test/models/notifications/NotificationRowSpec.scala, test/utils/ContactTypeHelperSpec.scala
AMLS-4675 | Further bug fix for NoSubject notifications
- none
- unit tests, run of Notification Feature from AC
=> AMLS-4675 | Further bug fix for NoSubject notifications

app/controllers/businessactivities/AccountantForAMLSRegulationsController.scala, app/controllers/businessactivities/BusinessFranchiseController.scala, app/controllers/businessactivities/EmployeeCountAMLSSupervisionController.scala, app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala, app/controllers/businessactivities/ExpectedBusinessTurnoverController.scala, app/controllers/businessactivities/HowManyEmployeesController.scala, app/controllers/businessactivities/IdentifySuspiciousActivityController.scala, app/controllers/businessactivities/InvolvedInOtherController.scala, app/controllers/businessactivities/NCARegisteredController.scala, app/controllers/businessactivities/RiskAssessmentController.scala, app/controllers/businessactivities/SummaryController.scala, app/controllers/businessactivities/TaxMattersController.scala, app/controllers/businessactivities/WhatYouNeedController.scala, app/controllers/businessactivities/WhoIsYourAccountantController.scala, conf/businessActivities.routes, test/controllers/businessactivities/AccountantForAMLSRegulationsControllerSpec.scala, test/controllers/businessactivities/BusinessFranchiseControllerSpec.scala, test/controllers/businessactivities/EmployeeCountAMLSSupervisionControllerSpec.scala, test/controllers/businessactivities/ExpectedAMLSTurnoverControllerSpec.scala, test/controllers/businessactivities/ExpectedBusinessTurnoverControllerSpec.scala, test/controllers/businessactivities/HowManyEmployeesControllerSpec.scala, test/controllers/businessactivities/IdentifiySuspiciousActivityControllerSpec.scala, test/controllers/businessactivities/InvolvedInOtherControllerSpec.scala, test/controllers/businessactivities/NCARegisteredControllerSpec.scala, test/controllers/businessactivities/RiskAssessmentControllerSpec.scala, test/controllers/businessactivities/SummaryControllerSpec.scala, test/controllers/businessactivities/TaxMattersControllerSpec.scala, test/controllers/businessactivities/WhoIsYourAccountantControllerSpec.scala
=> Amls 4637 businessactivities controller DI

app/controllers/businessmatching/BusinessTypeController.scala, app/controllers/businessmatching/TypeOfBusinessController.scala, conf/businessMatching.routes, test/controllers/businessmatching/BusinessTypeControllerSpec.scala, test/controllers/businessmatching/TypeOfBusinessControllerSpec.scala
Updated DI in business matching
Ran spec tests and regression tests, both passed.
=> AMLS 4635 | Updated DI in business matching

app/controllers/declaration/AddPersonController.scala, app/controllers/declaration/DeclarationController.scala, app/controllers/declaration/WhoIsRegisteringController.scala, conf/app.routes, test/controllers/declaration/AddPersonControllerSpec.scala, test/controllers/declaration/DeclarationControllerSpec.scala, test/controllers/declaration/WhoIsRegisteringControllerSpec.scala
Converted declaration controllers to DI
Unit tests
=> Amls 4695 - Declaration Controllers DI

app/models/package.scala, public/amls.js, public/autocomplete/location-autocomplete-canonical-list.json, public/autocomplete/location-autocomplete-graph.json
Fixed some issues with the Countries list. 
Manual tests and QAed.
=> AMLS 4492 fix

.github/PULL_REQUEST_TEMPLATE.md, generate-my-release-note.sh, generate-release-notes.sh, release_notes/AMLS-4697.txt
N/A
Generated first release note. Manual testing and group demo.
=> Added release note generation scripts and first release note

app/views/hvd/what_you_need.scala.html
Simple change to title of HVD - What you need page, but needed acceptance tests update.
Regression tests passed (regression tests needed updating - see pull request for acceptance tests)
=> AMLS-3976 | Added "HVD" to  "What you need" title

test/controllers/hvd/WhatYouNeedControllerSpec.scala
Fix failing build
N/A
Unit Test
=> Fix build WhatYouNeedController

test/controllers/msb/SendTheLargestAmountsOfMoneyControllerSpec.scala
Amended unit tests - quick PR for build pass
=> AMLS-4156 | Amended unit tests

app/views/declaration/register_responsible_person.scala.html
Changed visually hidden label on button (see image [on ticket](https://jira.tools.tax.service.gov.uk/browse/AMLS-4127)) No changes to acceptance tests required.
Ran regression tests
=> AMLS-4127 | Changed Business Activities to Responsible People

release_notes/AMLS-4127.txt
=> AMLS-4127 | Added release note

app/controllers/msb/SendMoneyToOtherCountryController.scala
Changed matching on whether edit was true or not so that the data is saved regardless of the page state
Unit tests passing
Manual Tested
=> AMLS-4156 | Amended matching on edit field

release_notes/AMLS-4127.txt, release_notes/AMLS-4156.txt, release_notes/AMLS-4354.txt, release_notes/AMLS-4460.txt, release_notes/AMLS-4669.txt, release_notes/AMLS-4697.txt, release_notes/AMLS-4702.txt, release_notes/AMLS-4703.txt, release_notes/AMLS-4856.txt, release_notes/releases/v4.246.0/v4.246.0-21-02-2019.txt
Generate release notes for v4.246.0
N/A
N/A
=> Generate release notes for v4.246.0

app/views/aboutthebusiness/letters_address.scala.html, release_notes/AMLS-4727.txt
Fixed fieldset legend on "Is this the right address to send you letters?"
Checked page using VO
=> AMLS-4727 | VO: Incorrect radio button group title

release_notes/AMLS-3717.txt, release_notes/AMLS-4344.txt, release_notes/AMLS-4381.txt, release_notes/AMLS-4727.txt, release_notes/AMLS-4728.txt, release_notes/AMLS-4734.txt, release_notes/AMLS-4748.txt, release_notes/releases/v4.257.0/v4.257.0-28-02-2019.txt
Generated release notes for v4.257.0
- none
- not applicable
=> Generated release notes for v4.257.0

release_notes/AMLS-4628.txt, release_notes/AMLS-4670.txt, release_notes/AMLS-4715.txt, release_notes/AMLS-4752.txt, release_notes/releases/v4.264.0/v4.264.0-05-03-2019.txt
=> Latest release notes

app/controllers/tradingpremises/ActivityStartDateController.scala, app/views/tradingpremises/activity_start_date.scala.html, release_notes/AMLS-3150.txt, test/controllers/tradingpremises/ActivityStartDateControllerSpec.scala, test/views/tradingpremises/activit_start_dateSpec.scala
address playback on the activity_start_date page
=> Amls 3150 - address playback on the activity_start_date page

release_notes/AMLS-3150.txt, release_notes/AMLS-3776.txt, release_notes/AMLS-4392.txt, release_notes/AMLS-4451.txt, release_notes/AMLS-4627.txt, release_notes/AMLS-4658.txt, release_notes/AMLS-4740.txt, release_notes/releases/v4.276.0/v4.276.0-12-03-2019.txt
Release notes for v4_276_0
N/A
N/A
=> Add rel notes for v4.276.0

app/views/supervision/summary.scala.html
Added unique tags for edit links on Check Your Answers Page as per QA request.
- none
- unit test
=> AMLS-4272 | Added unique tags for edit links on Check Your Answers Page

app/views/renewal/most_transactions.scala.html, release_notes/AMLS-4759.txt
Fixed legend on "Where did u send the most transactions..."
Visual inspection
=> AMLS-4759 | Fixed legend on "Where did u send the most transactions..."

release_notes/AMLS-4272.txt, release_notes/AMLS-4603.txt, release_notes/AMLS-4754.txt, release_notes/AMLS-4759.txt, release_notes/releases/v4.286.0/-19-03-2019.txt
=> Generated v4.286.0 release notes

app/views/confirmation/confirm_amendvariation.scala.html, app/views/confirmation/confirm_renewal.scala.html, app/views/confirmation/confirmation_new.scala.html, app/views/declaration/select_business_nominated_officer.scala.html, app/views/declaration/who_is_registering_common.scala.html, app/views/declaration/who_is_registering_this_registration.scala.html, app/views/declaration/who_is_registering_this_renewal.scala.html, app/views/declaration/who_is_registering_this_update.scala.html, app/views/payments/bank_details.scala.html, app/views/payments/ways_to_pay.scala.html, conf/messages, release_notes/AMLS-4716.txt, test/views/confirmation/BacsConfirmationTransitionalRenewalViewSpec.scala, test/views/confirmation/BacsConfirmationViewSpec.scala, test/views/confirmation/PaymentConfirmedTransitionalRenewalViewSpec.scala, test/views/confirmation/PaymentConfirmedViewSpec.scala, test/views/confirmation/SubmitRegistrationConfirmationViewSpec.scala, test/views/payments/bank_detailsSpec.scala
Updates as specified on [AMLS-4716](https://jira.tools.tax.service.gov.uk/browse/AMLS-4716)
Requires Acceptance Test change - pull request [here](https://github.com/hmrc/amls-acceptance-test/pull/153)
Ran spec tests, acceptance tests.
=> AMLS-4716 | Content updates on Declaration / Submission

generate-release-notes.sh
Change release notes generator to prompt for release tag. 
N/A
Local
=> update release note gen to prompt for tag

release_notes/AMLS-4272.txt, release_notes/AMLS-4603.txt, release_notes/AMLS-4754.txt, release_notes/AMLS-4759.txt, release_notes/releases/v4.286.0/-19-03-2019.txt
Revert release notes for v.286.0
N/A
N/A
=> Revert release notes for v.286.0

app/controllers/tradingpremises/RemoveTradingPremisesController.scala, app/views/tradingpremises/remove_trading_premises.scala.html, conf/tradingPremises.routes, release_notes/AMLS-4799.txt, test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
Remove address from URL string when removing trading premises
N/A
Local  Regression and QA
=> Remove address from URL string when removing trading premises

release_notes/AMLS-4272.txt, release_notes/AMLS-4603.txt, release_notes/AMLS-4716.txt, release_notes/AMLS-4733.txt, release_notes/AMLS-4754.txt, release_notes/AMLS-4757.txt, release_notes/AMLS-4758.txt, release_notes/AMLS-4759.txt, release_notes/AMLS-4770.txt, release_notes/AMLS-4796.txt, release_notes/releases/v4.296.0/v4.296.0-20-03-2019.txt
=> Generated release notes for release 4.296.0

release_notes/AMLS-4123.txt, release_notes/AMLS-4238.txt, release_notes/AMLS-4515.txt, release_notes/AMLS-4756.txt, release_notes/AMLS-4772.txt, release_notes/AMLS-4799.txt, release_notes/AMLS-4800.txt, release_notes/AMLS-4815.txt, release_notes/AMLS-4818.txt, release_notes/AMLS-4822.txt, release_notes/AMLS-4835.txt, release_notes/releases/v4.311.0/v4.311.0-05-04-2019.txt
Created release notes after deploying.
- none
- not applicable
=> Release notes 4.311

app/views/registrationamendment/section_list.scala.html, app/views/registrationprogress/registration_progress.scala.html, public/amls.css, release_notes/AMLS-4823.txt, test/controllers/RegistrationProgressControllerSpec.scala
As in the subject. Updated frontend css to not display double line when adding new service to application.
none
manually
=> AMLS-4823 | Updated css to not display double line for newly added sections to registration progress

app/config/ApplicationConfig.scala, app/connectors/PayApiConnector.scala, app/controllers/ConfirmationController.scala, app/controllers/payments/WaysToPayController.scala, app/models/payments/CreatePaymentResponse.scala, app/services/PaymentsService.scala, release_notes/AMLS-4769.txt, test/connectors/PayApiConnectorSpec.scala, test/controllers/ConfirmationControllerSpec.scala, test/controllers/payments/WaysToPayControllerSpec.scala, test/generators/PaymentGenerator.scala, test/models/payments/CreatePaymentResponseSpec.scala, test/services/PaymentsServiceSpec.scala
Updates as specified in Pull Request [here](https://github.com/hmrc/amls-frontend/pull/961). Some fixes to JSON parsing.
Spec tests and acceptance tests.
**Needs testing on QA.**
=> AMLS-4769 | New Payment Endpoint

app/controllers/renewal/AMLSTurnoverController.scala, app/controllers/renewal/CustomersOutsideUKController.scala, app/controllers/renewal/FXTransactionsInLast12MonthsController.scala, app/controllers/renewal/SendMoneyToOtherCountryController.scala, app/controllers/renewal/TotalThroughputController.scala, app/controllers/renewal/WhichCurrenciesController.scala, app/views/renewal/summary.scala.html, release_notes/AMLS-4837.txt, test/controllers/renewal/AMLSTurnoverControllerSpec.scala, test/controllers/renewal/CustomersOutsideUKControllerSpec.scala, test/controllers/renewal/FXTransactionsInLast12MonthsControllerSpec.scala, test/controllers/renewal/SendMoneyToOtherCountryControllerSpec.scala, test/controllers/renewal/TotalThroughputControllerSpec.scala, test/controllers/renewal/WhichCurrenciesControllerSpec.scala
Changing the positioning of the ASP question within the renewal flow to ask iit before HVD questions
https://github.com/hmrc/amls-stub/pull/122
Unit Tests
Manual Testing - New users have been created in stubs to fit **some** of the route cases
=> Amls 4837 - HVD/ASP renewal flow change

app/views/include/forms2/fieldset.scala.html, app/views/include/forms2/legend.scala.html, app/views/include/heading.scala.html, app/views/supervision/supervision_end_reasons.scala.html, conf/application.conf, release_notes/AMLS-4869.txt, release_notes/AMLS-4898.txt
Add h1 to legend for Box Input
Only non-conditional reveal one is on Supervision End Reasons
https://github.com/hmrc/amls-frontend/pull/1014
Visual testing.
Inspection of the html
=> AMLS-4872 AMLS-4898

conf/application.conf, release_notes/AMLS-4869.txt
Updates Assets Frontend to the latest version
Tested pages to check that they had not broken stylistically.
Ran unit tests and they still pass.
=> AMLS-4869: Updates Assets Frontend

test/controllers/renewal/PercentageOfCashPaymentOver15000ControllerSpec.scala
As above.
- none
- unit test run
=> AMLS-4717 | Fix to failing unit test.

conf/businessMatching.routes
Fix typo in PSR question URL
N/A
Unit + Regression
=> Fix typo in PSR question

app/views/estateagentbusiness/business_servicess.scala.html, app/views/estateagentbusiness/penalised_by_professional.scala.html, app/views/estateagentbusiness/penalised_under_estate_agents_act.scala.html, app/views/estateagentbusiness/redress_scheme.scala.html, app/views/include/forms2/fieldset.scala.html, app/views/include/forms2/legend.scala.html, release_notes/AMLS-4910.txt
Add h1 to legend for EAB
Manual inspection of elements
=> AMLS-4910: Add h1 to legend for EAB

app/controllers/renewal/RenewalProgressController.scala, app/views/include/services_sidebar.scala.html, app/views/registrationamendment/registration_amendment.scala.html, app/views/registrationprogress/registration_progress.scala.html, app/views/renewal/renewal_progress.scala.html, release_notes/AMLS-4832.txt, test/views/registrationprogress/registration_progressSpec.scala, test/views/renewal/renewal_progressSpec.scala
Added business name and services list to renewal's About your Business page. The link under the services list is hidden for renewal.
Unit testing, passes acceptance tests.
=> AMLS-4832 | Adding business name and services to renewal

release_notes/AMLS-3763.txt, release_notes/AMLS-4199.txt, release_notes/AMLS-4767.txt, release_notes/AMLS-4771.txt, release_notes/AMLS-4774.txt, release_notes/AMLS-4832.txt, release_notes/AMLS-4886.txt, release_notes/AMLS-4910.txt, release_notes/releases/v4.362.0/v4.362.0-08-05-2019.txt
=> release notes 4.362.0

app/models/renewal/InvolvedInOther.scala, conf/messages, release_notes/AMLS-4927.txt, test/models/renewal/InvolvedInOtherSpec.scala
Improve error messages EAB Renewal flow
=> Amls 4927 - renewal flow error messages

release_notes/AMLS-4838.txt, release_notes/AMLS-4915.txt, release_notes/AMLS-4921.txt, release_notes/AMLS-4926.txt, release_notes/AMLS-4927.txt, release_notes/AMLS-4957.txt, release_notes/AMLS-4989.txt, release_notes/AMLS-4991.txt, release_notes/AMLS-4997.txt, release_notes/releases/v4.375.0/v4.375.0-16-05-2019.txt
Release note after deploy 4.375.0
=> Release note after deploy 4.375.0

test/controllers/BacsConfirmationControllerSpec.scala
Fix failing build after merge of AMLS-4988
N/A
Unit
=> Fix failing spec after merge of AMLS-4988

conf/messages
Fix h1 issue in RP on declaration. 
N/A
Unit and Local + regression.
=> Fix rp declerartion h1

app/controllers/RegistrationProgressController.scala, test/controllers/RegistrationProgressControllerSpec.scala
Reverts hmrc/amls-frontend#1027
Revert Renewal changes until we get an answer from the business.
=> Revert "Amls 4957"

release_notes/AMLS-5025.txt
=> Adsded release notes

test/utils/DateOfChangeHelperSpec.scala
whilst waiting for the sprint planning, i added more unit tests to DateOfChangeHelper
=> added tests to DateOfChangeHelper to improve coverage

release_notes/AMLS-4943.txt, release_notes/AMLS-5003.txt, release_notes/AMLS-5025.txt, release_notes/releases/v4.386.0/v4.386.0-23-05-2019.txt
Generate release notes
N/A
N/A
=> Gen release notes

test/views/businessdetails/contacting_you_phoneSpec.scala
Fix for failing unit test.
- none
- unit test run
=> Failing unit test fix.

app/views/include/forms2/date.scala.html
=> AMLS-5018: Removes duplicate id from date

app/views/changeofficer/new_nominated_officer.scala.html, app/views/changeofficer/remove_responsible_person.scala.html, app/views/changeofficer/role_in_business.scala.html, app/views/changeofficer/still_employed.scala.html, release_notes/AMLS-4999.txt, test/views/changeofficer/new_nominated_officerSpec.scala, test/views/changeofficer/remove_responsible_personSpec.scala, test/views/changeofficer/role_in_businessSpec.scala, test/views/changeofficer/still_employedSpec.scala
Adding the back button functionality to the change officer flow.
Unit tests
Manual Tests
=> Amls 4999 - Add back button to change officer flow.

app/views/declaration/register_partners.scala.html, test/views/changeofficer/new_nominated_officerSpec.scala, test/views/declaration/register_partnersSpec.scala
=> Fixes failing unit tests for build

test/models/ReadStatusResponseSpec.scala
just chipping at the missing unittests coverage
=> Improve test coverage read status response

app/views/hvd/cash_payment.scala.html, app/views/hvd/cash_payment_first_date.scala.html, app/views/hvd/excise_goods.scala.html, app/views/hvd/expect_to_receive.scala.html, app/views/hvd/how_will_you_sell_goods.scala.html, app/views/hvd/linked_cash_payments.scala.html, app/views/hvd/percentage.scala.html, app/views/hvd/products.scala.html, app/views/hvd/receiving.scala.html, release_notes/AMLS-4919.txt, test/views/hvd/productsSpec.scala
Add h1 to legend for HVD flow
Unit Tested
Manual Tested
=> Amls 4919 - Add h1 to legend for HVD flow

conf/application.conf, release_notes/AMLS-4580.txt
Add google tag manager to content security policy
N/A
To be tested in Staging...
=> Add google tag manager to content security policy

conf/application.conf, release_notes/AMLS-4580.txt
Reverts hmrc/amls-frontend#1079
=> Revert "Add google tag manager to content security policy"

conf/application.conf
Update content security policy for GTM
https://github.com/hmrc/app-config-staging/pull/2781
To be tested in staging.
=> Update content security policy for GTM

conf/application.conf
Resolve conflicts and tidy up.
N/A
Local
=> Amls 4580 4

app/models/hvd/Hvd.scala, release_notes/AMLS-5058.txt
=> AMLS-5058 | Bug fix: Editing HVD Question does not lead to section being 'Updated'

app/views/confirmation/confirmation_bacs.scala.html, app/views/confirmation/confirmation_bacs_transitional_renewal.scala.html, release_notes/AMLS-5052.txt
=> AMLS-5052 | Bug fix: You have submitted page VO issue

app/views/supervision/another_body.scala.html, app/views/supervision/penalised_by_professional.scala.html
=> AMLS-5073 - fix to radio buttons not stacked bug

app/views/include/forms2/date.scala.html, app/views/tradingpremises/activity_start_date.scala.html, app/views/tradingpremises/agent_company_name.scala.html, app/views/tradingpremises/agent_partnership.scala.html, app/views/tradingpremises/business_structure.scala.html, app/views/tradingpremises/confirm_address.scala.html, app/views/tradingpremises/is_residential.scala.html, app/views/tradingpremises/msb_services.scala.html, app/views/tradingpremises/registering_agent_premises.scala.html, app/views/tradingpremises/remove_agent_premises_reasons.scala.html, app/views/tradingpremises/remove_trading_premises.scala.html, app/views/tradingpremises/what_does_your_business_do.scala.html, app/views/tradingpremises/where_are_trading_premises.scala.html, release_notes/AMLS-4922.txt, test/views/tradingpremises/agent_company_nameSpec.scala, test/views/tradingpremises/agent_partnershipSpec.scala, test/views/tradingpremises/remove_trading_premisesSpec.scala
Manual inspection
(Pages with multiple inputs to be covered in seperate tickets)
=> AMLS-4922 Accessibility for Trading Premises flow

app/views/bankdetails/bank_account_name.scala.html, app/views/bankdetails/bank_account_types.scala.html, app/views/bankdetails/has_bank_account.scala.html, release_notes/AMLS-4918.txt, test/views/bankdetails/bank_account_nameSpec.scala
Only 3 views are changed for this particular section. "Your bank accounts" page is an outlier and will not be done within this scope of work. "Bank account is uk" page will be a page split so will also not be done as part of this work.
Manual
Unit
=> AMLS-4918 - Bank details accessability changes

app/views/businessactivities/summary.scala.html
=> AMLS-4884: Bulleted list on cya for document ra

test/controllers/RetryPaymentControllerSpec.scala
=> attempt to fix the failing unit test

test/controllers/supervision/ProfessionalBodyMemberControllerSpec.scala
=> attempt 2 to fix the failing unit test

release_notes/AMLS-4580.txt, release_notes/AMLS-4745.txt, release_notes/AMLS-4884.txt, release_notes/AMLS-4918.txt, release_notes/AMLS-4919.txt, release_notes/AMLS-4922.txt, release_notes/AMLS-4950.txt, release_notes/AMLS-5019.txt, release_notes/AMLS-5052.txt, release_notes/AMLS-5058.txt, release_notes/AMLS-5064.txt, release_notes/releases/v4.433.0/v4.433.0-19-06-2019.txt
Generate release notes
N/A
N/A
=> Generate release notes

conf/messages, release_notes/AMLS-5113.txt
Change H1 for 'Is this right address to send you letters'
Manual Testing
Unit Testing
=> Amls 5113 - Change H1 for 'Is this right address to send you letters'

app/views/msb/business_use_an_ipsp.scala.html, app/views/msb/ce_transaction_in_next_12_months.scala.html, app/views/msb/expected_throughput.scala.html, app/views/msb/funds_transfer.scala.html, app/views/msb/fx_transaction_in_next_12_months.scala.html, app/views/msb/identify_linked_transactions.scala.html, app/views/msb/money_sources.scala.html, app/views/msb/most_transactions.scala.html, app/views/msb/send_largest_amounts_of_money.scala.html, app/views/msb/send_money_to_other_country.scala.html, app/views/msb/transactions_in_next_12_months.scala.html, app/views/msb/uses_foreign_currencies.scala.html, app/views/msb/which_currencies.scala.html, release_notes/AMLS-4923.txt, test/views/msb/business_use_an_ipspSpec.scala, test/views/msb/ce_transaction_in_next_12_monthsSpec.scala, test/views/msb/fx_transaction_in_next_12_monthsSpec.scala, test/views/msb/transactions_in_next_12_monthsSpec.scala
Accessibility fixes for MSB flow
Manually, unit tests
=> AMLS-4923: Accessibility for MSB flow

app/views/tradingpremises/summary_details.scala.html, conf/messages, release_notes/AMLS-5121.txt
Changing trading premises check your answers continue button
Unit/manual
=> Amls 5121 - Changing TP cya button

conf/messages, release_notes/AMLS-5101.txt
Change h1 for 2 questions in the HVD flow
Do you expect to receive cash payments of over €10,000 from customers you have not met in person?
to
Do you expect to receive cash payments of €10,000 or more from customers you have not met in person?
and 
How do you expect to receive cash payments of over €10,000 from customers you have not met?
to
How do you expect to receive cash payments of €10,000 or more from customers you have not met?
=> AMLS-5101 - update to HVD h1 titles

test/controllers/renewal/PercentageOfCashPaymentOver15000ControllerSpec.scala
Fix to failing unit test.
- none
- unit test run
=> Fix to failing unit test.

app/views/tcsp/service_provider_types.scala.html, app/views/tcsp/services_of_another_tcsp.scala.html, release_notes/AMLS-5128.txt
Fix incorrect error markup on TCSP flow
N/A
Local
=> Fix incorrect error markup on TCSP flow

app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala, app/controllers/businessactivities/ExpectedBusinessTurnoverController.scala, app/controllers/businessactivities/InvolvedInOtherController.scala, app/controllers/businessactivities/SummaryController.scala, app/views/businessactivities/summary.scala.html, release_notes/AMLS-5016.txt, test/controllers/businessactivities/ExpectedAMLSTurnoverControllerSpec.scala, test/controllers/businessactivities/ExpectedBusinessTurnoverControllerSpec.scala, test/controllers/businessactivities/InvolvedInOtherControllerSpec.scala, test/controllers/businessactivities/SummaryControllerSpec.scala, test/views/businessactivities/summarySpec.scala
Removed editable checks from three questions in business activities. Updated summary view accordingly and specs. Questions now are editable regardless of status of the application.
List of questions:
- How much total net profit does your business expect in the next 12 months from services you’re registering for anti-money laundering supervision?
- How much total net profit does your business expect in the next 12 months?
- Is your business involved in any other activities?
- acceptance tests need updating for this change
- unit tests
- manual tests
=> Amls 5016 - Questions editable in business activities

app/controllers/hvd/SummaryController.scala, app/views/hvd/summary.scala.html, release_notes/AMLS-5015.txt, test/controllers/hvd/SummaryControllerSpec.scala, test/views/hvd/summarySpec.scala
This supposed to be done as part of different ticket but was missed. Edit links were missing on check your answers page. This PR fixes that.
- none
- manually, unit tests
=> AMLS-5015 | Bug fix: HVD questions editable

app/controllers/businessactivities/WhatYouNeedController.scala, app/controllers/msb/MostTransactionsController.scala, app/controllers/msb/SendMoneyToOtherCountryController.scala, app/controllers/msb/UsesForeignCurrenciesController.scala, app/controllers/msb/WhatYouNeedController.scala, release_notes/AMLS-5187.txt, test/controllers/businessactivities/WhatYouNeedControllerSpec.scala, test/controllers/msb/MostTransactionsControllerSpec.scala, test/controllers/msb/SendMoneyToOtherCountryControllerSpec.scala, test/controllers/msb/WhatYouNeedControllerSpec.scala
After doing questions editable we've noticed redirection issues. It was caused by additional status checks on pages before pages without edit links. In this PR is fix for that.
- none
- manually, unit tests
=> Amls 5187 - Fix to redirection issues in MSB and Business Activities after making some questions editable

app/controllers/businessdetails/LettersAddressController.scala, test/controllers/businessdetails/LettersAddressControllerSpec.scala
Question Is this right address to send you letters was wiping out the data of two next questions if you didn't change your answer in edit mode.
- none
- manually, unit tests
=> Amls 4888 bugfix

app/controllers/msb/BranchesOrAgentsWhichCountriesController.scala, release_notes/AMLS-5116.txt
Fixed mis-aligned errors on MSB which-countries page (if other pages are affected, fix will need applied to them later).
Manual testing, ran unit tests
=> AMLS-5116 | Countries error message bug

project/FrontendBuild.scala
Latest auth version
N/A
Unit + Local
=> Latest auth version

release_notes/AMLS-4124.txt, release_notes/AMLS-4887.txt, release_notes/AMLS-4888.txt, release_notes/AMLS-4920.txt, release_notes/AMLS-4923.txt, release_notes/AMLS-4924.txt, release_notes/AMLS-4926.txt, release_notes/AMLS-4951.txt, release_notes/AMLS-4966-bug.txt, release_notes/AMLS-4966.txt, release_notes/AMLS-4992.txt, release_notes/AMLS-5015.txt, release_notes/AMLS-5016.txt, release_notes/AMLS-5101.txt, release_notes/AMLS-5103.txt, release_notes/AMLS-5110.txt, release_notes/AMLS-5113.txt, release_notes/AMLS-5116.txt, release_notes/AMLS-5120.txt, release_notes/AMLS-5121.txt, release_notes/AMLS-5125.txt, release_notes/AMLS-5128.txt, release_notes/AMLS-5133.txt, release_notes/AMLS-5142.txt, release_notes/AMLS-5187.txt, release_notes/AMLS-5214.txt, release_notes/releases/v4.434.0-v4.458/v4.434.0-v4.458-25-07-2019.txt
Like above.
- none
- not applicable
=> Release 4.456.0 release notes

app/connectors/AmlsConnector.scala, app/connectors/AmlsNotificationConnector.scala, app/utils/AuthAction.scala, project/FrontendBuild.scala
=> Auth wip update

app/models/hvd/CashPayment.scala, app/models/hvd/Hvd.scala, release_notes/AMLS-5186.txt, test/models/hvd/CashPaymentSpec.scala, test/models/hvd/HvdSpec.scala
HVD: application can be submitted with missing payment date
Manual
Unit
=> Amls 5186 - HVD: application can be submitted with missing payment date

app/utils/AuthAction.scala, test/controllers/actions/MockedAuthActions.scala, test/utils/AuthActionSpec.scala
Added groupIdentifier to retreivals in auth action
N/A
Unit Test + manual
=> Added groupIdentifier to retreivals in auth action

app/connectors/cache/DataCacheConnector.scala, app/controllers/changeofficer/Helpers.scala, app/controllers/changeofficer/NewOfficerController.scala, app/controllers/changeofficer/RemoveResponsiblePersonController.scala, app/controllers/changeofficer/RoleInBusinessController.scala, app/controllers/changeofficer/StillEmployedController.scala, app/utils/RepeatingSection.scala, release_notes/AMLS-5081.txt, test/controllers/changeofficer/NewOfficerControllerSpec.scala, test/controllers/changeofficer/RemoveResponsiblePersonControllerSpec.scala, test/controllers/changeofficer/RoleInBusinessControllerSpec.scala, test/controllers/changeofficer/StillEmployedControllerSpec.scala
Moving to the new Auth Client FE for Change Officer:
Unit tested
=> AMLS-5081 Change Officer: Moving to the new Auth Client FE

app/controllers/tcsp/AnotherTCSPSupervisionController.scala, app/controllers/tcsp/ComplexCorpStructureCreationController.scala, app/controllers/tcsp/OnlyOffTheShelfCompsSoldController.scala, app/controllers/tcsp/ProvidedServicesController.scala, app/controllers/tcsp/ServicesOfAnotherTCSPController.scala, app/controllers/tcsp/SummaryController.scala, app/controllers/tcsp/TcspTypesController.scala, app/controllers/tcsp/WhatYouNeedController.scala, release_notes/AMLS-5093.txt, test/controllers/tcsp/AnotherTCSPSupervisionControllerSpec.scala, test/controllers/tcsp/ComplexCorpStructureCreationControllerSpec.scala, test/controllers/tcsp/OnlyOffTheShelfCompsSoldControllerSpec.scala, test/controllers/tcsp/ProvidedServicesControllerSpec.scala, test/controllers/tcsp/ServicesOfAnotherTCSPControllerSpec.scala, test/controllers/tcsp/SummaryControllerSpec.scala, test/controllers/tcsp/TcspTypesControllerSpec.scala, test/controllers/tcsp/WhatYouNeedControllerSpec.scala
TCSP - Moving to the new Auth Client FE
Unit Tests
Acceptance tests passing locally (prior to review)
=> Amls 5093 - TCSP - Moving to the new Auth Client FE

conf/messages, release_notes/AMLS-5211.txt
=> Auth wip master 1

app/controllers/supervision/AnotherBodyController.scala, app/controllers/supervision/PenalisedByProfessionalController.scala, app/controllers/supervision/ProfessionalBodyMemberController.scala, app/controllers/supervision/SummaryController.scala, app/controllers/supervision/SupervisionEndController.scala, app/controllers/supervision/SupervisionEndReasonsController.scala, app/controllers/supervision/SupervisionStartController.scala, app/controllers/supervision/WhatYouNeedController.scala, app/controllers/supervision/WhichProfessionalBodyController.scala, release_notes/AMLS-5092.txt, test/controllers/supervision/AnotherBodyControllerSpec.scala, test/controllers/supervision/PenalisedByProfessionalControllerSpec.scala, test/controllers/supervision/ProfessionalBodyMemberControllerSpec.scala, test/controllers/supervision/SummaryControllerSpec.scala, test/controllers/supervision/SupervisionEndControllerSpec.scala, test/controllers/supervision/SupervisionEndReasonsControllerSpec.scala, test/controllers/supervision/SupervisionStartControllerSpec.scala, test/controllers/supervision/WhatYouNeedControllerSpec.scala, test/controllers/supervision/WhichProfessionalBodyControllerSpec.scala
Supervision - Moving to the new Auth Client FE
Unit test passing (local)
Acceptance tests passing (prior QA testing)
=> Amls 5092 - Supervision - Moving to the new Auth Client FE

app/views/include/status/rightpanel_submissionreadyforreview.scala.html, release_notes/AMLS-5199.txt
Added ID to 45 days paragraph for optimizely selector
N/A
Local + Unit
=> Added ID to 45 days paragraph for optimizely selector

app/views/include/status/rightpanel_submissionreadyforreview.scala.html, release_notes/AMLS-5199.txt
Pull master into auth wip.
N/A
N/A
=> Update auth wip master 2

app/views/include/forms2/country_autocomplete.scala.html, app/views/include/forms2/currency.scala.html, release_notes/AMLS-5207.txt
Implementation of Visually Hidden Error content on all the Countries in the service
Unit/Acceptance/Manual (local)
=> Amls 5207 - Implementation of Visually Hidden Error content on all the Countries in the service

app/models/asp/ServicesOfBusiness.scala, app/models/estateagentbusiness/Service.scala, app/models/tradingpremises/TradingPremisesMsbServices.scala, app/views/asp/summary.scala.html, app/views/businessmatching/summary.scala.html, app/views/estateagentbusiness/summary.scala.html, app/views/tradingpremises/msb_services.scala.html, app/views/tradingpremises/summary_details.scala.html, release_notes/AMLS-5010.txt
Implemented getMessage helper method to use it for alphabetical sorting.
- none
- manually, unit tests
=> Amls 5010 - getMessage instead of toString

app/connectors/AmlsConnector.scala, app/controllers/withdrawal/WithdrawApplicationController.scala, app/controllers/withdrawal/WithdrawalReasonController.scala, release_notes/AMLS-5095.txt, test/controllers/withdrawal/WithdrawApplicationControllerSpec.scala, test/controllers/withdrawal/WithdrawalReasonControllerSpec.scala
Auth implementation for withdrawal section.
Unit Test
=> Amls 5095 - Withdrawal section auth

app/controllers/hvd/CashPaymentController.scala, app/controllers/hvd/CashPaymentFirstDateController.scala, app/controllers/hvd/ExciseGoodsController.scala, app/controllers/hvd/ExpectToReceiveCashPaymentsController.scala, app/controllers/hvd/HowWillYouSellGoodsController.scala, app/controllers/hvd/HvdDateOfChangeController.scala, app/controllers/hvd/LinkedCashPaymentsController.scala, app/controllers/hvd/PercentageOfCashPaymentOver15000Controller.scala, app/controllers/hvd/ProductsController.scala, app/controllers/hvd/ReceiveCashPaymentsController.scala, app/controllers/hvd/SummaryController.scala, app/controllers/hvd/WhatYouNeedController.scala, release_notes/AMLS-5085.txt, test/controllers/hvd/CashPaymentFirstDateControllerSpec.scala, test/controllers/hvd/CashPaymentOverTenThousandEurosControllerSpec.scala, test/controllers/hvd/ExciseGoodsControllerSpec.scala, test/controllers/hvd/ExpectToReceiveCashPaymentsControllerSpec.scala, test/controllers/hvd/HowWillYouSellGoodsControllerSpec.scala, test/controllers/hvd/HvdDateOfChangeControllerSpec.scala, test/controllers/hvd/LinkedCashPaymentsControllerSpec.scala, test/controllers/hvd/PercentageOfCashPaymentOver15000ControllerSpec.scala, test/controllers/hvd/ProductsControllerSpec.scala, test/controllers/hvd/ReceiveCashPaymentsControllerSpec.scala, test/controllers/hvd/SummaryControllerSpec.scala, test/controllers/hvd/WhatYouNeedControllerSpec.scala
HVD - Moving to the new Auth Client FE
Unit Tests
=> Amls 5085 - HVD - Moving to the new Auth Client FE

app/connectors/AmlsConnector.scala, app/controllers/deregister/DeRegisterApplicationController.scala, app/controllers/deregister/DeregistrationReasonController.scala, release_notes/AMLS-5083.txt, test/controllers/deregister/DeRegisterApplicationControllerSpec.scala, test/controllers/deregister/DeregistrationReasonControllerSpec.scala
Deregister section - auth implementation and spec changes.
Unit tests
=> Amls 5083 - Deregister auth implementation

app/controllers/estateagentbusiness/BusinessServicesController.scala, app/controllers/estateagentbusiness/PenalisedByProfessionalController.scala, app/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActController.scala, app/controllers/estateagentbusiness/ResidentialRedressSchemeController.scala, app/controllers/estateagentbusiness/ServicesDateOfChangeController.scala, app/controllers/estateagentbusiness/SummaryController.scala, app/controllers/estateagentbusiness/WhatYouNeedController.scala, release_notes/AMLS-5084.txt, test/controllers/estateagentbusiness/BusinessServicesControllerSpec.scala, test/controllers/estateagentbusiness/PenalisedByProfessionalControllerSpec.scala, test/controllers/estateagentbusiness/PenalisedUnderEstateAgentsActControllerSpec.scala, test/controllers/estateagentbusiness/ResidentialRedressSchemeControllerSpec.scala, test/controllers/estateagentbusiness/ServicesDateOfChangeControllerSpec.scala, test/controllers/estateagentbusiness/SummaryControllerSpec.scala, test/controllers/estateagentbusiness/WhatYouNeedControllerSpec.scala
EAB controllers full auth implementation with spec changes
Auth
Unit tested and local run through the journey
=> Alms 5084: EAB - Moving to the new Auth Client FE

app/connectors/AmlsConnector.scala, app/controllers/payments/BankDetailsController.scala, app/controllers/payments/TypeOfBankController.scala, app/controllers/payments/WaysToPayController.scala, app/services/PaymentsService.scala, release_notes/AMLS-5087.txt, test/controllers/payments/BankDetailsControllerSpec.scala, test/controllers/payments/TypeOfBankControllerSpec.scala, test/controllers/payments/WaysToPayControllerSpec.scala
Updated Payments Auth
Spec tests and coverage report (Statement coverage 90.28% | Branch coverage....: 86.28%)
=> AMLS 5087 | Payments Auth update

app/connectors/AmlsConnector.scala, app/controllers/payments/BankDetailsController.scala, app/controllers/payments/WaysToPayController.scala, app/services/StatusService.scala, test/controllers/payments/WaysToPayControllerSpec.scala
Fixed auth implementation in payments controllers.
- none
- manually, regression
=> BUG-FIX: Auth implementation correction in payments controllers

app/utils/AuthAction.scala, project/FrontendBuild.scala, release_notes/AMLS-5309.txt
Update Auth use User in place of Admin
N/A
Local + Regression + Unit
=> Update Auth use User in place of Admin

app/config/ApplicationConfig.scala, app/views/error.scala.html, app/views/include/main.scala.html, app/views/include/main2.scala.html, app/views/include/notifications_your_messages.scala.html, app/views/include/status/rightpanel_submissionreadyforreview.scala.html, app/views/include/whatyouneed.scala.html, app/views/submission/bad_request.scala.html, app/views/submission/duplicate_enrolment.scala.html, app/views/submission/duplicate_submission.scala.html, app/views/submission/wrong_credential_type.scala.html, conf/application.conf, public/amls.css, release_notes/AMLS-5308.txt
=> AMLS-5308 | error pages changed to AMP

app/controllers/tradingpremises/ActivityStartDateController.scala, release_notes/AMLS-5297.txt, test/controllers/tradingpremises/ActivityStartDateControllerSpec.scala
As above.
- none
- manually, regression on TP section
=> AMLS-5297 | BUG-FIX: Editing business start date doesn't update trading premises section

app/config/ApplicationConfig.scala, app/models/amp/Amp.scala, app/models/amp/MongoDateTimeFormats.scala, conf/application.conf, release_notes/AMLS-5281.txt, test/models/amp/AmpSpec.scala, test/models/amp/MongoDateTimeFormatsSpec.scala
Add AMLS front end AMP section model. 
Implements:
- Is Complete 
- Section 
- Reads / Writes
N/A
Unit Tests + Regression Pack
=> Amls 5281 - AMLS front end AMP section model 

app/controllers/LandingController.scala, release_notes/AMLS-5282.txt, test/controllers/LandingControllerWithAmendmentsSpec.scala
AMLS front end - landing controller data has changed for AMP
N/A
Unit Test
=> AMLS front end - landing controller data has changed for AMP

app/config/ApplicationConfig.scala, conf/application.conf, release_notes/AMLS-5355.txt
Change the url of AMP FE to be more seamless to the user
https://github.com/hmrc/amls-art-market-participant-frontend/pull/19
https://github.com/hmrc/mdtp-frontend-routes/pull/1145
Local Dev Testing
=> Change the url of AMP FE to be more seamless to the user

app/config/ApplicationConfig.scala, conf/application.conf
New config for redirect to AMP svc
https://github.com/hmrc/app-config-staging/pull/3321
Local + Unit
=> New config for redirect to AMP svc

conf/application.conf
=> Correct url for local dev

conf/messages, release_notes/AMLS-5343.txt
Add approval content for amp on approval screens in rp section
N/A
Local
=> Add approval content for amp on approval screens in rp section

app/views/businessmatching/updateservice/change_services.scala.html, conf/app.routes, conf/messages, release_notes/AMLS-5366.txt, test/views/businessmatching/updateservice/change_servicesSpec.scala
Correct content 'pre application variation' P2
Visual Testing
=> Amls 5366 - Correct content 'pre application variation' P2

app/views/payments/ways_to_pay.scala.html, conf/messages, release_notes/AMLS-5412.txt, test/views/payments/ways_to_paySpec.scala
Updated 'How do you want to pay your fees'.
H1 change, **will need acceptance test updates**
Manual, ran and updated spec tests
=> AMLS-5412 | Update 'How do you want to pay your fees'

app/controllers/businessmatching/updateservice/remove/WhatDateRemovedController.scala, app/views/businessmatching/updateservice/add/business_applied_for_psr_number.scala.html, app/views/businessmatching/updateservice/add/fit_and_proper.scala.html, app/views/businessmatching/updateservice/add/msb_subservices.scala.html, app/views/businessmatching/updateservice/add/select_activities.scala.html, app/views/businessmatching/updateservice/add/trading_premises.scala.html, app/views/businessmatching/updateservice/add/what_do_you_do_here.scala.html, app/views/businessmatching/updateservice/add/which_fit_and_proper.scala.html, app/views/businessmatching/updateservice/add/which_trading_premises.scala.html, app/views/date_of_change.scala.html, release_notes/AMLS-5428.txt
Updated button text in pre-app variation. May need acceptance test update?
Manual testing, ran spec tests.
=> AMLS-5428 | Updated button text in pre-app variation

app/utils/AuthAction.scala, app/views/unauthorised_role.scala.html, release_notes/AMLS-5460.txt, test/utils/AuthActionSpec.scala
Improve unauthorised user journey where no active session. 
N/A
QA
=> Amls 5460 enhanced

app/views/businessmatching/updateservice/add/add_more_activities.scala.html, release_notes/AMLS-5427.txt
Made radio buttons inline, rather than stacked.
Manual testing
=> AMLS-5427 | Radio buttons on "Do you want to add another service?"

app/controllers/businessmatching/updateservice/ChangeSubSectorHelper.scala, release_notes/AMLS-5455.txt, test/controllers/businessmatching/updateservice/ChangeSubSectorHelperSpec.scala
As above. How to reproduce is in the ticket.
- none
- manually
- unit tests
- regression
=> Amls 5455 - Bug fix: MSB Section not showing as updated when MSB activities have been changed

app/views/responsiblepeople/detailed_answers.scala.html, release_notes/AMLS-5390.txt, test/views/responsiblepeople/detailed_answersSpec.scala
Updated RP "Check your answers" styling
Manual testing, updated unit tests
=> AMLS-5390 | Updated RP "Check your answers" styling

app/views/tradingpremises/summary_details.scala.html, release_notes/AMLS-5389.txt, test/views/tradingpremises/summary_detailsSpec.scala
=> Amls 5389 | New summary page layout - trading premises

app/views/tradingpremises/summary_details.scala.html, release_notes/AMLS-5389.txt, test/views/tradingpremises/summary_detailsSpec.scala
Reverts hmrc/amls-frontend#1231
=> Revert "Amls 5389 | New summary page layout - trading premises"

app/views/tradingpremises/summary_details.scala.html, release_notes/AMLS-5389.txt, test/views/tradingpremises/summary_detailsSpec.scala
Reverts hmrc/amls-frontend#1232
=> Revert "Revert "Amls 5389 | New summary page layout - trading premises""

app/controllers/tradingpremises/AgentCompanyDetailsController.scala, app/controllers/tradingpremises/AgentCompanyNameController.scala, app/controllers/tradingpremises/AgentNameController.scala, app/controllers/tradingpremises/AgentPartnershipController.scala, app/controllers/tradingpremises/BusinessStructureController.scala, app/controllers/tradingpremises/RegisteringAgentPremisesController.scala, release_notes/AMLS-5482.txt, test/controllers/tradingpremises/AgentCompanyDetailsControllerSpec.scala, test/controllers/tradingpremises/AgentCompanyNameControllerSpec.scala, test/controllers/tradingpremises/AgentNameControllerSpec.scala, test/controllers/tradingpremises/AgentPartnershipControllerSpec.scala, test/controllers/tradingpremises/BusinessStructureControllerSpec.scala, test/controllers/tradingpremises/RegisteringAgentPremisesControllerSpec.scala
Fixed routing in Trading Premises edit mode
Manual testing, unit tests
=> AMLS 5482 | Bugfix: Routing in Trading Premises edit mode

app/models/tradingpremises/TradingPremises.scala, release_notes/AMLS-5484.txt
Fixed isComplete logic in Trading Premises
Manual testing, passed unit tests
=> AMLS 5484 | Bugfix: Trading Premises isComplete logic

public/amls.css, release_notes/AMLS-5485.txt
Fixed colour of login event button. Slightly different CSS to @tempertemper's solution (see [ticket](https://jira.tools.tax.service.gov.uk/browse/AMLS-5485))
Manually tested (see ticket)
=> AMLS-5485 | Fixed colour of login event button

app/views/hvd/summary.scala.html, release_notes/AMLS-5394.txt, test/controllers/hvd/SummaryControllerSpec.scala, test/views/hvd/summarySpec.scala
Updated HVD 'Check your answers' page
Manual test, unit tests
=> AMLS-5394 | Updated HVD 'Check your answers' page

app/views/asp/summary.scala.html, release_notes/AMLS-5391.txt, test/views/asp/summarySpec.scala
ASP check your answers changes
Manual
=> Amls 5391 - ASP CYA refactor

app/models/supervision/ProfessionalBodies.scala, app/views/supervision/summary.scala.html, release_notes/AMLS-5392.txt, test/views/supervision/summarySpec.scala
CYA and spec changes to allow for new CYA refactor
Manual
Unit
=> AMLS-5392 | Supervision CYA

app/views/estateagentbusiness/summary.scala.html, release_notes/AMLS-5393.txt, test/views/estateagentbusiness/summarySpec.scala
Check your answers changes for EAB section
Unit
Manual
=> Amls 5393 - CYA for EAB section

app/views/businessmatching/updateservice/add/update_services_summary.scala.html, app/views/businessmatching/updateservice/remove/remove_activities_summary.scala.html, release_notes/AMLS-5397.txt, test/controllers/businessmatching/updateservice/remove/RemoveBusinessTypesSummaryControllerSpec.scala
This contains updated layout for pre app variation: add service and remove services CYA pages.
- none
- manually
=> Amls 5397 - New layout CYA page for pre app variation

app/utils/AuthAction.scala, release_notes/AMLS-5499.txt, test/utils/AuthActionSpec.scala
Fix to look for active enrolments only (Merge back - please do not delete the branch)
N/A
Unit + Local + Regression
=> Auth error - fix to look for active enrolments only

app/views/tcsp/summary.scala.html, release_notes/AMLS-5395.txt, test/views/tcsp/summarySpec.scala
TCSP new CYA format
N/A
Local + Unit + Regression
=> TCSP new CYA format

app/views/components/back_link.scala.html, release_notes/AMLS-5512.txt
Removed tabindex from back button
Manual test
=> AMLS-5512 | Removed tabindex from back button

app/views/confirmation/confirm_amendvariation.scala.html, app/views/confirmation/confirm_renewal.scala.html, app/views/include/forms2/input.scala.html, app/views/include/heading.scala.html, app/views/status/status_deregistered.scala.html, app/views/status/status_expired.scala.html, app/views/status/status_incomplete.scala.html, app/views/status/status_not_submitted.scala.html, app/views/status/status_rejected.scala.html, app/views/status/status_renewal_incomplete.scala.html, app/views/status/status_renewal_not_submitted.scala.html, app/views/status/status_renewal_submitted.scala.html, app/views/status/status_revoked.scala.html, app/views/status/status_submitted.scala.html, app/views/status/status_supervised.scala.html, app/views/status/status_withdrawn.scala.html, public/amls.css, release_notes/AMLS-5507.txt
Moved secondary headings above H1s
Manual, unit tests
=> AMLS-5507 | Move secondary heading above H1

app/controllers/renewal/MostTransactionsController.scala, release_notes/AMLS-5509.txt, test/controllers/renewal/MostTransactionsControllerSpec.scala
Fix renewal loop bug for ASP, MSB (MT) and TCSP
N/A
Local + Unit + Regression
=> Fix renewal loop bug for ASP, MSB (MT) and TCSP

app/views/renewal/summary.scala.html, release_notes/AMLS-5398.txt, test/controllers/renewal/SummaryControllerSpec.scala, test/views/renewal/summarySpec.scala
Renewal check you answers page new layout
Unit
Manual
=> Amls 5398 - Renewal CYA changes

app/views/include/forms2/legend.scala.html, app/views/include/main2.scala.html, app/views/include/status/rightpanel_incomplete.scala.html, app/views/include/status/rightpanel_renewalincomplete.scala.html, app/views/include/status/rightpanel_renewalnotsubmitted.scala.html, release_notes/AMLS-5508.txt
- Removed asterisks from print.css link
- Removed "submit" from <a> on status pages
- Separated out <div> from <span> in legend.scala.html
- Removed aria-hidden from "No Thanks" in UR banner
Manual testing, unit tests
=> AMLS-5508 | Accessibility fixes

app/views/payments/ways_to_pay.scala.html, conf/messages, release_notes/AMLS-5468.txt, test/views/payments/ways_to_paySpec.scala
Add paragraph text to How do you want to pay your fees?
N/A
Local + Unit
=> Add paragraph text to How do you want to pay your fees?

README.md, app/models/FormTypes.scala, app/models/businessmatching/BusinessAppliedForPSRNumber.scala, app/models/businessmatching/CompanyRegistrationNumber.scala, app/models/businessmatching/TypeOfBusiness.scala, conf/messages, release_notes/AMLS-5511.txt, test/controllers/renewal/SummaryControllerSpec.scala, test/models/businessmatching/BusinessAppliedForPSRNumberSpec.scala, test/models/businessmatching/CompanyRegistrationNumberSpec.scala, test/models/businessmatching/TypeOfBusinessSpec.scala
Error messages for pre app
Manually
Unit
=> Amls 5511 - Pre app variation error messages

app/models/FormTypes.scala, app/models/businessdetails/ActivityStartDate.scala, app/models/businessdetails/CorrespondenceAddressNonUk.scala, app/models/businessdetails/CorrespondenceAddressUk.scala, app/models/businessdetails/RegisteredOffice.scala, conf/messages, release_notes/AMLS-5438.txt, test/controllers/businessdetails/ActivityStartDateControllerSpec.scala, test/controllers/businessdetails/CorrespondenceAddressNonUkControllerSpec.scala, test/controllers/businessdetails/CorrespondenceAddressUkControllerSpec.scala, test/controllers/businessdetails/RegisteredOfficeNonUKControllerSpec.scala, test/controllers/businessdetails/RegisteredOfficeUKControllerSpec.scala, test/controllers/responsiblepeople/address/AdditionalAddressUKControllerSpec.scala, test/controllers/responsiblepeople/address/CurrentAddressControllerUKSpec.scala, test/models/FormTypesSpec.scala, test/models/businessdetails/ActivityStartDateSpec.scala, test/models/businessdetails/ContactingYouEmailSpec.scala, test/models/businessdetails/CorrespondenceAddressNonUkSpec.scala, test/models/businessdetails/CorrespondenceAddressUkSpec.scala, test/models/businessdetails/RegisteredOfficeSpec.scala, test/models/businessdetails/VATRegisteredSpec.scala, test/models/businessmatching/ConfirmPostcodeSpec.scala, test/models/responsiblepeople/ContactDetailsSpec.scala, test/models/responsiblepeople/PersonAddressSpec.scala, test/models/responsiblepeople/VATRegisteredSpec.scala
=> Amls 5438 - New error messages for business details

app/models/amp/Amp.scala, test/controllers/amp/AmpControllerSpec.scala, test/models/amp/AmpSpec.scala, test/services/LandingServiceSpec.scala, test/services/UpdateMongoCacheServiceSpec.scala, test/services/amp/AmpCacheServiceSpec.scala
As above. Models needed changed due to changes to file name and Json names in AMP.
DON'T MERGE - Until AMP branch is also merged as they depend on each other
Unit
Manual
=> AMLS-5479 | Changing AMP models for differ in content

app/views/notifications/your_messages.scala.html, public/amls.css, release_notes/AMLS-4881.txt, test/views/notifications/your_messagesSpec.scala
As above. More in the ticket.
- none
- manually
=> Amls 4881 - New notifications layout

app/config/AmlsHeaderCarrierForPartialsConverter.scala
Fix to crypto for HC converter for Play 2.6
N/A
Local + Regression
=> Fix to crypto for HC converter for Play 2.6

app/views/changeofficer/role_in_business.scala.html, release_notes/AMLS-5514.txt
=> AMLS-5514 | Changed paragraph text to hint in change officer flow for role in business question.

app/config/ApplicationConfig.scala, conf/application.conf, release_notes/AMLS-5588.txt
Correct feedback and get help urls to work in all environments
N/A
Local
=> Correct feedback and get help urls to work in all environments

app/models/FormTypes.scala, conf/messages, release_notes/AMLS-5440.txt, test/models/FormTypesSpec.scala
=> AMLS-5442 | Bank Details error changes

app/connectors/AuthConnector.scala, app/controllers/amp/AmpController.scala, app/models/auth/CredentialRole.scala, project/MicroService.scala, test/controllers/amp/AmpControllerSpec.scala, test/controllers/responsiblepeople/DetailedAnswersControllerSpec.scala, test/models/responsiblepeople/ApprovalFlagsSpec.scala, test/utils/JsonMappingSpec.scala
Added few exclusions  for test coverage as well as tests for a few methods.
- none
- N/A
=> Test coverage

app/views/bankdetails/bank_account_account_iban.scala.html, test/views/bankdetails/bank_account_non_uk_ibanSpec.scala
=> AMLS-4002 | More review fixes

app/controllers/tcsp/ServicesOfAnotherTCSPController.scala, app/models/tcsp/ProvidedServices.scala, app/models/tcsp/ServicesOfAnotherTCSP.scala, conf/messages, release_notes/AMLS-5444.txt, test/models/tcsp/ProvidedServicesSpec.scala, test/models/tcsp/ServicesOfAnotherTCSPSpec.scala
=> AMLS 5444 | Updated TCSP error messages

app/views/asp/what_you_need.scala.html, app/views/bankdetails/what_you_need.scala.html, app/views/businessactivities/what_you_need.scala.html, app/views/businessdetails/what_you_need.scala.html, app/views/components/user_attention_saving.scala.html, app/views/estateagentbusiness/what_you_need.scala.html, app/views/hvd/what_you_need.scala.html, app/views/msb/what_you_need.scala.html, app/views/renewal/what_you_need.scala.html, app/views/responsiblepeople/what_you_need.scala.html, app/views/responsiblepeople/who_must_register.scala.html, app/views/supervision/what_you_need.scala.html, app/views/tcsp/what_you_need.scala.html, app/views/tradingpremises/what_you_need.scala.html, conf/messages, public/amls.css, release_notes/AMLS-5567.txt, test/views/responsiblepeople/who_must_registerSpec.scala, test/views/tradingpremises/what_you_needSpec.scala
implementation of Auto save panel on what you need pages
Unit
Manual
=> AMLS-5567 | Changes to what you need save button

app/config/ApplicationConfig.scala
=> Fix protocol

app/config/ApplicationConfig.scala, conf/application.conf
Correct configuration for protocol
N/A
Local + Unit + Regression
=> Correct configuration for protocol

app/config/ApplicationConfig.scala, conf/application.conf
First attempt to correct http (should be https) issue in staging
N/A
Local (To test in staging)
=> First attempt to correct http (should be https) issue in staging

app/models/payments/Payment.scala, release_notes/AMLS-5587.txt, test/generators/PaymentGenerator.scala
Reverts hmrc/amls-frontend#1280
=> Revert "Amls 5587" - Pay API changes

app/controllers/declaration/RenewRegistrationController.scala, app/models/declaration/RenewRegistration.scala, app/models/payments/Payment.scala, app/views/declaration/renew_registration.scala.html, release_notes/AMLS-5587.txt, test/generators/PaymentGenerator.scala
Amls 5587 make pay api change revertible by changing Payment description field to an option.
https://github.com/hmrc/amls/pull/282
Local + Regression
=> Amls 5587 make pay api change revertible

app/controllers/declaration/RenewRegistrationController.scala, app/models/declaration/RenewRegistration.scala, app/views/declaration/renew_registration.scala.html, app/views/registrationamendment/registration_amendment.scala.html, app/views/registrationprogress/registration_progress.scala.html, release_notes/AMLS-5595.txt, test/controllers/declaration/RenewRegistrationControllerSpec.scala, test/models/declaration/RenewRegistrationSpec.scala, test/views/businessdetails/renew_registrationSpec.scala
Changing the subheading "sections" and "sections to complete" to "business information"
Manually
=> Amls 5595 - Updating H2 on about your business page

app/controllers/declaration/RenewRegistrationController.scala, app/models/declaration/RenewRegistration.scala, app/models/estateagentbusiness/EstateAgentBusiness.scala, app/models/estateagentbusiness/RedressScheme.scala, app/views/declaration/renew_registration.scala.html, app/views/estateagentbusiness/redress_scheme.scala.html, app/views/estateagentbusiness/summary.scala.html, conf/messages, release_notes/AMLS-5320.txt, test/controllers/declaration/RenewRegistrationControllerSpec.scala, test/controllers/estateagentbusiness/ResidentialRedressSchemeControllerSpec.scala, test/models/declaration/RenewRegistrationSpec.scala, test/models/estateagentbusiness/EstateAgentBusinessSpec.scala, test/models/estateagentbusiness/RedressSchemeSpec.scala, test/views/businessdetails/renew_registrationSpec.scala, test/views/estateagentbusiness/redress_schemeSpec.scala
Removal of ombudsman services and the other field on the redress scheme page within estate agency business section.
Unit
Manual
=> Amls 5320 - Redress scheme changes

project/FrontendBuild.scala
Upgraded mongo version to 7.22.0
- none
- unit tests run
=> Upgraded mongo version to 7.22.0

app/views/confirmation/payment_confirmation.scala.html, app/views/confirmation/payment_confirmation_amendvariation.scala.html, app/views/confirmation/payment_confirmation_renewal.scala.html, app/views/confirmation/payment_confirmation_transitional_renewal.scala.html, conf/messages, release_notes/AMLS-5620.txt, test/controllers/PaymentConfirmationControllerSpec.scala, test/views/confirmation/PaymentConfirmedTransitionalRenewalViewSpec.scala, test/views/confirmation/PaymentConfirmedViewSpec.scala
=> AMLS-5620 | Removed remaining references to 45 days and updated content on confirmation pages

app/views/bankdetails/bank_account_account_iban.scala.html, app/views/bankdetails/bank_account_account_number_non_uk.scala.html, app/views/bankdetails/bank_account_account_uk.scala.html, app/views/bankdetails/bank_account_is_uk.scala.html, app/views/include/forms2/input.scala.html, release_notes/AMLS-5621.txt
=> AMLS-5621 | Removed title attribute from input template

app/views/bankdetails/summary.scala.html, app/views/include/forms2/detailsSummary.scala.html, release_notes/AMLS-5624.txt
=> AMLS-5624 | New CYA layout for bank details

app/controllers/responsiblepeople/address/CurrentAddressDateOfChangeController.scala, app/controllers/responsiblepeople/address/CurrentAddressNonUKController.scala, app/controllers/responsiblepeople/address/CurrentAddressUKController.scala, app/models/DateOfChange.scala, release_notes/AMLS-5596.txt, test/controllers/responsiblepeople/address/CurrentAddressDateOfChangeControllerSpec.scala
There was not right routing from date of change of home address details page. User was landing on Your responsible people instead of landing on consecutive question page or detailed answers. In this PR there's fix for this.
- none
- manually
- unit tests
=> Amls 5596 - Bug fix: Date of change routing not working in RP section

app/controllers/businessdetails/RegisteredOfficeDateOfChangeController.scala, app/controllers/tradingpremises/AgentNameController.scala, app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala, app/controllers/tradingpremises/WhereAreTradingPremisesController.scala
fixed date of change in other places to not use today's date
none
- unit tests
- regression
=> AMLS-5596 | fixed date of change in other places to not use today's date

app/views/businessmatching/updateservice/add/select_activities.scala.html, app/views/include/forms2/checkbox.scala.html, app/views/include/forms2/fieldsetWithErrorGroup.scala.html, app/views/include/forms2/radio.scala.html, release_notes/AMLS-5631.txt
As above
- none
- unit tests
- manually
=> Amls 5631 - Hook hint text up to inputs on services select in pre-app and pre-app variation

app/views/include/forms2/legend.scala.html, public/amls.css, release_notes/AMLS-5618.txt
=> AMLS-5618 | Updated legend field to remove div

public/amls.css
This ticket was to add the latest WCAG changes to the radio button outlines once selected and margins around multiple errors.
=> AMLS-5619 | Added latest radio button css changes and error margins

release_notes/AMLS-4002.txt, release_notes/AMLS-5293.txt, release_notes/AMLS-5320.txt, release_notes/AMLS-5354.txt, release_notes/AMLS-5435.txt, release_notes/AMLS-5436.txt, release_notes/AMLS-5440.txt, release_notes/AMLS-5444.txt, release_notes/AMLS-5539.txt, release_notes/AMLS-5546.txt, release_notes/AMLS-5567.txt, release_notes/AMLS-5587.txt, release_notes/AMLS-5590.txt, release_notes/AMLS-5592.txt, release_notes/AMLS-5595.txt, release_notes/AMLS-5600.txt, release_notes/AMLS-5636.txt, release_notes/releases/v4.697.0/v4.697.0-23-01-2020.txt
=> Generated release notes for release 4.697.0

app/views/bankdetails/bank_account_account_uk.scala.html, release_notes/AMLS-5628.txt
=> AMLS-5628 | Added panel classes to sort code and account number input

app/controllers/NotificationController.scala, app/views/components/back_link_notifications.scala.html, app/views/msb/summary.scala.html, app/views/notifications/your_messages.scala.html, app/views/satisfaction_survey.scala.html, app/views/tcsp/summary.scala.html, release_notes/AMLS-5686-5687-5688-5689.txt, test/views/notifications/your_messagesSpec.scala, test/views/satisfaction_surveySpec.scala
As above. In MSB/TCSP cya, notifications view, satisfaction survey.
- none
- manually
- unit tests
=> Amls 5686 5687 5688 5689 | Fixed ID's on some view components

app/views/include/main2.scala.html, conf/messages, public/amls.css, release_notes/AMLS-5669.txt
=> AMLS-5669 | Changed the url and content for 1 Click testing

release_notes/AMLS-5686-5687-5688-5689.txt, release_notes/releases/v4.718.0/v4.718.0-03-02-2020.txt
=> Generate release note

app/views/businessmatching/company_registration_number.scala.html, app/views/include/forms2/input.scala.html, release_notes/AMLS-5663.txt
=> AMLS-5663 | Hook company reg number hint text up to input

app/views/responsiblepeople/who_must_register.scala.html, release_notes/AMLS-5651.txt, test/views/responsiblepeople/who_must_registerSpec.scala
=> AMLS-5651 | Removed Autosaving banner from 'who you need to register' page in RP section

conf/messages, release_notes/AMLS-5642.txt
=> AMLS-5642 | Update link text on 'Manage your anti-money laundering supervision'

app/views/tradingpremises/remove_agent_premises_reasons.scala.html, conf/messages, release_notes/AMLS-5674.txt
Changed content when displaying conditional reveal from the other input on the removal of agents trading premise page.
Manual
=> AMLS-5674 | Changed other input content

app/views/payments/type_of_bank.scala.html, release_notes/AMLS-5709.txt
=> Amls 5709 - Made "type of bank" inputs inline

app/views/tcsp/provided_services.scala.html, release_notes/AMLS-5721.txt
Added a gutter on option other within the provided services page in the TCSP section.
Manual
=> Amls 5721 - Adding gutter to tcsp input

app/views/asp/summary.scala.html, app/views/estateagentbusiness/summary.scala.html, app/views/supervision/summary.scala.html, release_notes/AMLS-5685.txt
As above added <dl> tags to summary pages.
- none
- manually
=> Amls 5685 - EAB, ASP, Supervision CYA markup issue

app/controllers/tradingpremises/RemoveTradingPremisesController.scala, test/controllers/tradingpremises/RemoveTradingPremisesControllerSpec.scala
Fix remove RP with line ID when pending bug
N/A
Local + Unit
=> Fix remove RP with line ID when pending bug

app/models/hvd/CashPaymentFirstDate.scala, app/models/hvd/PaymentMethods.scala, app/models/hvd/Products.scala, conf/messages, release_notes/AMLS-5446.txt, test/controllers/hvd/CashPaymentFirstDateControllerSpec.scala, test/models/hvd/CashPaymentFirstDateSpec.scala, test/models/hvd/PaymentMethodSpec.scala, test/models/hvd/ProductsSpec.scala, test/models/hvd/ReceiveCashPaymentsSpec.scala
=> Amls 5446 - HVD Error messages updates

app/controllers/businessmatching/updateservice/add/SelectBusinessTypeController.scala, app/controllers/businessmatching/updateservice/add/WhatDoYouDoHereController.scala, app/controllers/businessmatching/updateservice/remove/WhatDateRemovedController.scala, app/models/DateOfChange.scala, app/models/FormTypes.scala, app/models/businessmatching/BusinessAppliedForPSRNumber.scala, app/models/businessmatching/BusinessMatchingMsbServices.scala, conf/messages, release_notes/AMLS-5447.txt, test/controllers/estateagentbusiness/ServicesDateOfChangeControllerSpec.scala, test/models/DateOfChangeSpec.scala, test/models/businessmatching/BusinessAppliedForPSRNumberSpec.scala, test/models/businessmatching/BusinessMatchingMsbServicesSpec.scala
Pre app variation flow error message changes.
Unit
Manual
=> Amls 5447 - Pre app error changes

app/controllers/bankdetails/BankDetailsController.scala, app/models/bankdetails/BankAccount.scala, app/models/bankdetails/BankDetails.scala, release_notes/AMLS-5653.txt, test/controllers/bankdetails/BankAccountHasIbanControllerSpec.scala, test/controllers/bankdetails/BankAccountIbanControllerSpec.scala, test/controllers/bankdetails/BankAccountIsUKControllerSpec.scala, test/controllers/bankdetails/BankAccountNonUKControllerSpec.scala, test/controllers/bankdetails/BankAccountTypeControllerSpec.scala, test/controllers/bankdetails/BankAccountUKControllerSpec.scala, test/models/bankdetails/BankDetailsSpec.scala
Fix - Bank account section should show Incomplete
N/A
Local + Unit
=> Fix - Bank account section should show Incomplete

app/controllers/payments/BankDetailsController.scala, app/controllers/payments/TypeOfBankController.scala, app/controllers/payments/WaysToPayController.scala, app/views/payments/bank_details.scala.html, app/views/payments/type_of_bank.scala.html, app/views/payments/ways_to_pay.scala.html, release_notes/AMLS-5723.txt, test/controllers/payments/TypeOfBankControllerSpec.scala, test/controllers/payments/WaysToPayControllerSpec.scala, test/views/payments/bank_detailsSpec.scala, test/views/payments/type_of_bankSpec.scala, test/views/payments/ways_to_paySpec.scala
=> Amls 5723 | Updated secondary level heading in renewal payments

app/views/businessmatching/updateservice/add/which_fit_and_proper.scala.html, app/views/businessmatching/updateservice/add/which_trading_premises.scala.html, release_notes/AMLS-5744.txt
=> AMLS-5744 | Changed paragraph text to hint.

conf/messages, release_notes/AMLS-5760.txt
=> Amls 5760 | Changed fees to fee in payment flow

app/views/responsiblepeople/experience_training.scala.html, release_notes/AMLS-5725.txt
Changes estate agency business to estate agent.
Unit
Manual
=> AMLS-5725 | Changed error message in RP exp training

app/controllers/ConfirmationController.scala, app/controllers/declaration/DeclarationController.scala, app/controllers/payments/BankDetailsController.scala, app/controllers/payments/TypeOfBankController.scala, app/controllers/payments/WaysToPayController.scala, app/utils/DeclarationHelper.scala, app/views/confirmation/confirm_renewal.scala.html, app/views/payments/bank_details.scala.html, app/views/payments/type_of_bank.scala.html, app/views/payments/ways_to_pay.scala.html, release_notes/AMLS-5761.txt, test/controllers/declaration/DeclarationControllerSpec.scala, test/controllers/payments/BankDetailsControllerSpec.scala, test/controllers/payments/TypeOfBankControllerSpec.scala, test/controllers/payments/WaysToPayControllerSpec.scala, test/utils/DeclarationHelperSpec.scala, test/views/payments/bank_detailsSpec.scala, test/views/payments/type_of_bankSpec.scala, test/views/payments/ways_to_paySpec.scala
=> Amls 5761 - Updated secondary headings in payment journeys

app/views/applicationstatus/how_to_pay.scala.html, conf/messages, release_notes/AMLS-5758.txt, test/views/applicationstatus/how_to_paySpec.scala
Tidy up how to pay page
N/A
Local + Unit
=> Tidy up how to pay page

app/controllers/renewal/AMLSTurnoverController.scala, app/models/renewal/AMLSTurnover.scala, app/views/renewal/amls_turnover.scala.html, app/views/renewal/involved_in_other.scala.html, conf/messages, release_notes/AMLS-5229.txt, test/controllers/renewal/AMLSTurnoverControllerSpec.scala, test/views/renewal/amls_turnoverSpec.scala
As above.
- AC need updating
- manually
=> Amls 5229 | Content updates in renewal section

app/services/SectionsProvider.scala, release_notes/AMLS-5678.txt, test/controllers/RegistrationProgressControllerSpec.scala, test/controllers/renewal/RenewalProgressControllerSpec.scala
=> AMLS-5678 | Fixed ordering of services on registration progress page

app/models/deregister/DeregistrationReason.scala, app/models/withdrawal/WithdrawalReason.scala, app/views/deregister/deregistration_reason.scala.html, app/views/withdrawal/withdrawal_reason.scala.html, conf/app.routes, conf/messages, release_notes/AMLS-5765.txt, test/models/deregister/DeregistrationReasonSpec.scala, test/models/withdrawal/WithdrawalReasonSpec.scala
Content changes, H1 changes, URL changes for Deregister and Withdrawal reasons pages.
Unit
Manual
=> Amls 5765 - Withdraw and Deregister reasons content update

app/controllers/bankdetails/YourBankAccountsController.scala, app/models/responsiblepeople/ResponsiblePerson.scala, app/models/tradingpremises/TradingPremises.scala, release_notes/AMLS-5754.txt
Newly added ^ will now appear at the top of the list for users.
Unit
Manual
=> Amls 5754 - Reverse order of RP, bank details and trading premises

app/views/businessmatching/summary.scala.html
Updated ID field for PSR number so separate fields were accessible in acceptance tests.
Release notes not needed as ticket already in master. This is a fix for acc tests
=> AMLS-5804-fix | Updated ID field for PSR number

app/controllers/businessmatching/updateservice/ChangeSubSectorHelper.scala, release_notes/AMLS-5774.txt, test/controllers/businessmatching/updateservice/ChangeSubSectorHelperSpec.scala
As above, fix for this.
- none
- manually
- unit tests
=> Amls 5774 - System isn't recognising a change to the PSR number

app/controllers/businessmatching/updateservice/add/BusinessAppliedForPSRNumberController.scala, app/models/flowmanagement/AddBusinessTypeFlowModel.scala, release_notes/AMLS-5812.txt, test/controllers/businessmatching/updateservice/add/BusinessAppliedForPSRNumberControllerSpec.scala
As above.
- none
- manually
- unit tests
=> Amls 5812 - Fix: Going 'Back' to pre app after answering No to PSR number breaks the flow

app/controllers/StatusController.scala, release_notes/AMLS-5826.txt
=> Amls 5826 | Application ready to submit button on status page goes to wrong place fix

app/views/renewal/send_money_to_other_country.scala.html, release_notes/AMLS-5805.txt, test/views/renewal/send_money_to_other_countrySpec.scala
As above.
https://github.com/hmrc/amls-acceptance-test/pull/295
- manually
- unit tests
=> Amls 5805 | Updated title to include word 'renewal' in sending money to other countries

app/controllers/StatusController.scala, app/views/include/status/trade_information_find_out.scala.html, release_notes/AMLS-5806.txt, test/controllers/StatusControllerSpec.scala
As above.
- none
- manually
- unit tests
=> Amls 5806 | Added default content to can or cannot trade information

app/views/status/components/registration_status.scala.html, conf/messages, release_notes/AMLS-5795.txt, test/views/status/your_registrationSpec.scala
As above.
- none
- manually
- unit tests
=> Amls 5795 - Fix to missing status information when date not available.

app/views/include/forms2/currency.scala.html, release_notes/AMLS-5832.txt
=> Amls 5832 | Linked label to input field in currency component

app/config/ApplicationConfig.scala, app/views/include/main2.scala.html, conf/application.conf, public/amls.css, release_notes/AMLS-5870.txt
Added banner alongside feature toggle for covid19 link
=> Amls 5870 - Covid 19 banner

app/views/include/main2.scala.html, public/amls.css
=> AMLS-5870 | Added top and bottom padding to banner

release_notes/AMLS-5832.txt, release_notes/releases/v4.808.0/v4.808.0-25-03-2020.txt
=> Generated release notes for release 4.808.0

conf/messages, release_notes/AMLS-5880.txt
Users name removed from error message on BA manage affairs page. 
Manually
=> AMLS-5880 | Personalised error message change

app/views/responsiblepeople/fit_and_proper_notice.scala.html, release_notes/AMLS-5840.txt
Visually hidden text removal for screen readers.
=> Amls 5840 Duplicate button text

app/models/bankdetails/BankAccountSubsteps.scala, release_notes/AMLS-5839.txt, test/models/bankdetails/AccountSpec.scala
Changed order of sort number and account number error messages
Manually
Unit
=> Amls 5839 - Reordered error message UK bank account

app/views/bankdetails/bank_account_account_uk.scala.html, app/views/businessactivities/business_employees.scala.html, app/views/businessactivities/business_employees_amls_supervision.scala.html, app/views/businessdetails/contacting_you_phone.scala.html, app/views/businessdetails/vat_registered.scala.html, app/views/businessmatching/company_registration_number.scala.html, app/views/businessmatching/psr_number.scala.html, app/views/include/forms2/input.scala.html, app/views/msb/business_use_an_ipsp.scala.html, app/views/msb/ce_transaction_in_next_12_months.scala.html, app/views/msb/fx_transaction_in_next_12_months.scala.html, app/views/msb/transactions_in_next_12_months.scala.html, app/views/renewal/ce_transactions_in_last_12_months.scala.html, app/views/renewal/fx_transaction_in_last_12_months.scala.html, app/views/renewal/transactions_in_last_12_months.scala.html, app/views/responsiblepeople/contact_details.scala.html, app/views/responsiblepeople/person_uk_passport.scala.html, app/views/responsiblepeople/registered_for_self_assessment.scala.html, app/views/responsiblepeople/vat_registered.scala.html, app/views/tcsp/another_tcsp_supervision.scala.html, conf/messages, release_notes/AMLS-5724.txt
As above. Detailed description in the ticket.
- none
- regression
- manual
=> Amls 5724 | Updated numeric inputs in the service

public/amls.css, release_notes/AMLS-5728.txt
=> AMLS-5728 | Changed colour background on confirmation page

app/views/include/forms2/date.scala.html, release_notes/AMLS-5831.txt
=> Amls 5844 - Removed whitespace from ariaDescribedBy

app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala, app/controllers/eab/EabController.scala, app/models/DateOfChange.scala, app/models/eab/Eab.scala, app/models/estateagentbusiness/EstateAgentBusiness.scala, app/services/businessmatching/BusinessMatchingService.scala, app/utils/DateOfChangeHelper.scala, conf/eab.routes, release_notes/AMLS-5850.txt, test/controllers/eab/EabControllerSpec.scala, test/models/eab/EabSpec.scala, test/utils/DateOfChangeHelperSpec.scala
Reverts hmrc/amls-frontend#1405
=> Revert "Amls 5850 - Missing Date Of Change in EAB Flow"

app/config/ApplicationConfig.scala, app/controllers/LandingController.scala, app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala, app/models/eab/Eab.scala, app/models/estateagentbusiness/ClientMoneyProtectionScheme.scala, app/models/estateagentbusiness/EstateAgentBusiness.scala, app/models/estateagentbusiness/PenalisedUnderEstateAgentsAct.scala, app/models/estateagentbusiness/ProfessionalBody.scala, app/models/estateagentbusiness/RedressScheme.scala, app/models/estateagentbusiness/Service.scala, app/services/SectionsProvider.scala, app/services/SubmissionService.scala, app/services/businessmatching/BusinessMatchingService.scala, app/views/login_event.scala.html, conf/application.conf, release_notes/AMLS-5779.txt, test/controllers/estateagentbusiness/BusinessServicesControllerSpec.scala, test/models/eab/EabSpec.scala, test/models/estateagentbusiness/ClientMoneyProtectionSchemeSpec.scala, test/services/SubmissionServiceSpec.scala, test/services/UpdateMongoCacheServiceSpec.scala
Reverted code retargeted at branch "phase-3-letting-agents"
N/A
N/A
=> Revert "Revert "Amls 5779 - Letting Agent DES Integration""

app/controllers/businessmatching/updateservice/RemoveBusinessTypeHelper.scala, app/controllers/eab/EabController.scala, app/models/DateOfChange.scala, app/models/eab/Eab.scala, app/models/estateagentbusiness/EstateAgentBusiness.scala, app/services/businessmatching/BusinessMatchingService.scala, app/utils/DateOfChangeHelper.scala, conf/eab.routes, release_notes/AMLS-5850.txt, test/controllers/eab/EabControllerSpec.scala, test/models/eab/EabSpec.scala, test/utils/DateOfChangeHelperSpec.scala
Re introduce: https://github.com/hmrc/amls-frontend/pull/1405
=> Re introduce PR 1405

release_notes/AMLS-5096.txt, release_notes/AMLS-5724.txt, release_notes/AMLS-5728.txt, release_notes/AMLS-5831.txt, release_notes/AMLS-5840.txt, release_notes/AMLS-5880.txt, release_notes/releases/v4.827.0/v4.827.0-22-04-2020.txt
Added release notes for v4.827.0
=> Added release notes for v4.827.0

app/views/include/forms2/date.scala.html, release_notes/AMLS-5722.txt
This is a new PR for existing work that has been reviewed and tested (closed PR link below). Was needed for commit signatures
https://github.com/hmrc/amls-frontend/pull/1406
Fully
=> Amls 5722 rebase - changing date fields

app/controllers/businessactivities/ExpectedAMLSTurnoverController.scala, app/models/businessactivities/ExpectedAMLSTurnover.scala, app/views/businessactivities/expected_amls_turnover.scala.html, conf/messages, release_notes/AMLS-5673.txt, test/views/businessactivities/expected_amls_turnoverSpec.scala
This has already been reviewed and tested and is a new rebased branch of 5673. This may however need another review as it has had master merged.
https://github.com/hmrc/amls-frontend/pull/1408
Fully
=> Amls 5673 rebase - Money laundering regulation content update

conf/messages, release_notes/AMLS-5876.txt, test/views/tcsp/summarySpec.scala
This is a new PR for existing work that has been reviewed and tested (closed PR link below). Was needed for commit signatures
https://github.com/hmrc/amls-frontend/pull/1411
Fully
=> Amls 5876 rebase - Other content throughout service 

app/views/status/your_registration.scala.html, release_notes/AMLS-5895.txt
Removed header class from status pages
Unit
Manual
=> AMLS-5895 | Removed header class from status pages 

app/views/include/submit_application.scala.html, conf/messages, release_notes/AMLS-5882.txt, test/controllers/RegistrationProgressControllerSpec.scala
AMLS-5882 | Fix Incorrect markup on the AYB page
N/A
LocaL + Unit
=> AMLS-5882 | Fix Incorrect markup on the AYB page

app/controllers/deregister/DeregistrationReasonController.scala, release_notes/AMLS-5830.txt, test/controllers/deregister/DeregistrationReasonControllerSpec.scala
Amls 5830 | Fix missing radio option when submitting error on de-register reason
N/A
Local + Unit
=> Amls 5830 | Fix missing radio option when submitting error on de-register reason

app/views/declaration/register_responsible_person.scala.html, release_notes/AMLS-5841.txt
=> Amls 5841 - Removed blue sidebar from Responsible people page

app/views/include/submit_application.scala.html, app/views/renewal/application_submit.scala.html, conf/messages, release_notes/AMLS-5883.txt
Fix repeated visually hidden text
N/A
Local + Unit
=> AMLS-5883 | Fix repeated visually hidden text

app/controllers/responsiblepeople/address/NewHomeAddressDateOfChangeController.scala, app/models/responsiblepeople/NewHomeDateOfChange.scala, conf/messages, release_notes/AMLS-5884.txt, test/controllers/responsiblepeople/address/NewHomeAddressDateOfChangeControllerSpec.scala, test/models/responsiblepeople/NewHomeDateOfChangeSpec.scala
Changed model validation and specs
unit
manual
=> AMLS-5884 | Newhomedateofchange changes

app/views/include/forms2/fieldsetWithErrorGroup.scala.html, app/views/include/forms2/input.scala.html, release_notes/AMLS-5913.txt, test/views/include/fieldsetWithErrorGroupSpec.scala, test/views/include/inputSpec.scala
Fix aria-describedby where there is an error and hint text
N/A
Unit + Local
=> AMLS-5913 | Fix aria-describedby where there is an error and hint text

app/views/supervision/summary.scala.html, release_notes/AMLS-5815.txt, test/views/supervision/summarySpec.scala
Supervision CYA changes
N/A
Local + Unit
=> AMLS-5815 | Supervision CYA changes

release_notes/AMLS-5808.txt, release_notes/AMLS-5809.txt, release_notes/AMLS-5810.txt, release_notes/AMLS-5811.txt, release_notes/AMLS-5815.txt, release_notes/AMLS-5820.txt, release_notes/AMLS-5877.txt, release_notes/AMLS-5919.txt, release_notes/releases/v4.847.0/v4.847.0-13-05-2020.txt
Generate release notes for v4.847.0
N/A
N/A
=> Generate release notes for v4.847.0

app/config/ApplicationConfig.scala, app/controllers/LoginEventController.scala, app/views/login_event.scala.html, test/views/login_eventSpec.scala
Fix redress redirect to eab from interrupt page
N/A
Local + Unit
=> Fix redress redirect to eab from interrupt page

app/config/ApplicationConfig.scala
Correct redress redirect
N/A
Local
=> Correct redress redirect

release_notes/AMLS-5779.txt, release_notes/AMLS-5848.txt, release_notes/AMLS-5850.txt, release_notes/releases/v4.853.0/v4.853.0-19-05-2020.txt
Added release notes for v4.853.0
=> Added release notes for v4.853.0

app/views/businessdetails/summary.scala.html, conf/messages, release_notes/AMLS-5925.txt
=> Amls 5925 - address for letters content update

app/models/hvd/HowWillYouSellGoods.scala, app/models/hvd/Products.scala, app/models/hvd/SalesChannel.scala, app/views/hvd/summary.scala.html, release_notes/AMLS-5821.txt, test/models/hvd/HowWillYouSellGoodsSpec.scala, test/models/hvd/ProductsSpec.scala, test/models/hvd/SalesChannelSpec.scala
As above.
- none
- manual
- unit tests
=> Amls 5821 | CYA updates in HVD

app/views/asp/summary.scala.html, release_notes/AMLS-5816.txt
=> Amls 5816 | CYA updates in ASP

app/views/include/forms2/fieldsetWithErrorGroup.scala.html, release_notes/AMLS-5934.txt
As above. Added missing bracket and additionally put the closing div's inside the if/else statement.
- none
- manually
=> Amls 5934 | DAC markup issue fix.

app/views/start.scala.html, conf/messages, release_notes/AMLS-5432.txt, test/views/startSpec.scala
As above.
- none
- manually
- unit tests
=> Amls 5432 | Updates to content on start/landing page

project/FrontendBuild.scala, project/build.properties, project/plugins.sbt, release_notes/AMLS-5753.txt
=> Amls 5753 | Updated app dependencies

app/models/tcsp/ProvidedServices.scala, app/views/tcsp/summary.scala.html, conf/messages, release_notes/AMLS-5814.txt, test/models/tcsp/TcspServiceSpec.scala, test/views/tcsp/summarySpec.scala
=> Amls 5814 - TCSP CYA changes

release_notes/AMLS-5432.txt, release_notes/AMLS-5753.txt, release_notes/AMLS-5759.txt, release_notes/AMLS-5803.txt, release_notes/AMLS-5807.txt, release_notes/AMLS-5814.txt, release_notes/AMLS-5816.txt, release_notes/AMLS-5818.txt, release_notes/AMLS-5819.txt, release_notes/AMLS-5821.txt, release_notes/AMLS-5879.txt, release_notes/AMLS-5925.txt, release_notes/AMLS-5934.txt, release_notes/releases/v4.865.0/v4.865.0-28-05-2020.txt
Added release notes for v4.865.0
=> Added release notes for v4.865.0

app/models/supervision/Supervision.scala, release_notes/AMLS-5936.txt, test/models/supervision/SupervisionSpec.scala
=> Amls 5936 | Bug fix: Supervision section should say not started instead incomplete when adding ASP or TCSP

app/models/enrolment/TaxEnrolment.scala, app/services/AuthEnrolmentsService.scala, app/services/SubmissionService.scala, test/services/AuthEnrolmentsServiceSpec.scala, test/services/SubmissionServiceSpec.scala
This is just to check if enrolment with the safeId only will succeed in QA. After test will be reverted.
- none
- unit tests
-regression
=> AMLS-5918 | QA enrolments test with SafeId

app/models/enrolment/TaxEnrolment.scala, app/services/AuthEnrolmentsService.scala, app/services/SubmissionService.scala, test/services/AuthEnrolmentsServiceSpec.scala, test/services/SubmissionServiceSpec.scala
Reverts hmrc/amls-frontend#1478
=> Revert "AMLS-5918 | QA enrolments test with SafeId"

app/config/ApplicationConfig.scala, app/services/UpdateMongoCacheService.scala, public/amls.css, public/characterCount.js, release_notes/AMLS-5917.txt, upversion-templates.sh
Remove TODO from code
N/A
Unit
=> Amls 5917 | Remove TODO from code

app/views/accessibility/accessibility_statement.scala.html
=> AMLS-5842 | Added security target on link

app/views/businessactivities/involved_in_other_name.scala.html, app/views/include/forms2/textarea.scala.html, app/views/renewal/involved_in_other.scala.html, app/views/responsiblepeople/experience_training.scala.html, app/views/responsiblepeople/training.scala.html, app/views/supervision/penalised_by_professional.scala.html, app/views/supervision/supervision_end_reasons.scala.html, public/amls.css, release_notes/AMLS-5935.txt, test/views/include/textAreaSpec.scala
and made characterCounter grey
^
Manually
- [?] Requires acceptance test run.
=> AMLS-5935 | Updated supervision end reasons H1

conf/application.conf, test/models/governmentgateway/EnrolmentRequestSpec.scala
As above.
- none
- unit tests run
=> Amls | Removed unused toggle

README.md, app/views/include/main.scala.html, app/views/include/main2.scala.html
=> AMLS-BetaHeadingRemoval | Removal of beta heading

app/models/autocomplete/LocationGraphTransformer.scala, project/FrontendBuild.scala, test/models/autocomplete/GovUkCountryDataProviderSpec.scala, test/models/autocomplete/LocationGraphTransformerSpec.scala
Change uses of whitelist to blacklist
Locally with; sbt clean compile test
=> language change to allowList

app/views/msb/expected_throughput.scala.html, app/views/renewal/total_throughput.scala.html, conf/messages, test/views/msb/what_you_needSpec.scala, test/views/renewal/total_throughputSpec.scala, test/views/renewal/what_you_needSpec.scala
[AMLS content changes for Money Service Business]
sbt test (unit tests) passed
=> DLS-4056 Money Service Business Content Changes

conf/messages, test/views/tcsp/what_you_needSpec.scala
[Trust Service Provider content changes]
passes unit tests
=> DLS-4058 Trust Service Provider content changes

app/views/tcsp/services_of_another_tcsp.scala.html, app/views/tradingpremises/what_you_need.scala.html, conf/messages
[Change of description in Trading Premises and Trust or Company service provider to include virtual offices content]
unit tests run
=> DLS-4059 virtual office content update

conf/messages
[Further content changes for Trust or Company Service Provider]
sbt tests run
=> DLS-4059 new content changes

.bsp/sbt.json, .gitignore, app/controllers/businessmatching/CheckCompanyController.scala, app/controllers/businessmatching/MsbSubSectorsController.scala, app/controllers/businessmatching/PSRNumberController.scala, app/controllers/businessmatching/RegisterServicesController.scala, app/modules/Module.scala, app/services/flowmanagement/PageRouter.scala, app/services/flowmanagement/Router.scala, app/services/flowmanagement/flowrouters/businessmatching/ChangeSubSectorRouter.scala, app/services/flowmanagement/pagerouters/businessmatching/subsectors/MsbSubSectorsPageRouter.scala, app/services/flowmanagement/pagerouters/businessmatching/subsectors/NoPsrNumberPageRouter.scala, app/services/flowmanagement/pagerouters/businessmatching/subsectors/PSRNumberPageRouter.scala, app/views/businessmatching/check_company_is_not_registered.scala.html, conf/businessMatching.routes, conf/messages, test/controllers/businessmatching/MsbSubSectorsControllerSpec.scala, test/controllers/businessmatching/PSRNumberControllerSpec.scala, test/utils/RouterMocks.scala
=> Dls 4442 New page for experiment 

app/services/cache/MongoCacheClient.scala, conf/application.conf, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/views/include/textAreaSpec.scala
This PR navigates amls-frontend to use the new hmrc-mongo.
Unit and acceptance tests pass.
=> DLS-5616 Mongo Library Upgrade

app/models/FeeResponse.scala, app/models/notifications/NotificationDetails.scala, app/models/notifications/NotificationResponse.scala, app/models/notifications/NotificationRow.scala, test/models/notifications/NotificationDetailsSpec.scala, test/models/notifications/NotificationRowSpec.scala
=> [DLS-5617] Formatting Date

app/views/include/forms2/country_autocomplete.scala.html
reapplying the previous fix for DLS-5812, due to recent reverts of the service.
=> DLS-5812 REDO - AMLS - Empty option for country drop-down

conf/messages
=> DDCYLS-2329: Corrected Typo in 'withdraw.reason.lbl.button'

app/views/status/components/registration_status.scala.html
Adding registration number to registration status
=> DDCYLS-3003

app/models/notifications/NotificationDetails.scala, test/models/notifications/NotificationDetailsSpec.scala
Reverts hmrc/amls-frontend#1553
=> Revert "DDCYLS-3992 Corrected regex for parsing XML/HTML secure message string"

app/models/businessactivities/AccountantsAddress.scala, app/models/responsiblepeople/PersonAddress.scala, test/models/businessactivities/AccountantsAddressSpec.scala, test/models/responsiblepeople/PersonAddressSpec.scala
=> DDCYLS-4231 | Fix issue with valid addresses being shown as incomplete

app/views/Layout.scala.html, app/views/declaration/DeclareView.scala.html, app/views/deregister/DeregistrationReasonView.scala.html, app/views/withdrawal/WithdrawalReasonView.scala.html, public/submitButtonDisable.js, test/views/declaration/DeclareViewSpec.scala, test/views/deregister/DeregistrationReasonViewSpec.scala, test/views/withdrawal/WithdrawalReasonViewSpec.scala
https://github.com/hmrc/amls-frontend/assets/29063729/aeed897c-c9ba-403f-b302-1b29fe05a16e
=> DDCYLS-4184 Added JS for button disable when submitting to API

app/models/notifications/ContactType.scala, test/models/notifications/ContactTypeSpec.scala
=> DDCYLS-3903 Revert ContactType changes

app/models/responsiblepeople/ResponsiblePerson.scala
TaskRow function updated to not incomplete when an totally empty model is saved into the database & there is already a complete one in there as well
=> DDCYLS-3059

app/connectors/PayApiConnector.scala, app/controllers/SubmissionController.scala, app/controllers/businessactivities/WhatYouNeedController.scala, app/controllers/renewal/WhatYouNeedController.scala, app/controllers/responsiblepeople/PositionWithinBusinessStartDateController.scala, app/controllers/responsiblepeople/WhatYouNeedController.scala, app/controllers/tradingpremises/WhatDoesYourBusinessDoController.scala, app/controllers/tradingpremises/WhatYouNeedController.scala, app/services/businessdetails/PreviouslyRegisteredService.scala, app/services/cache/MongoCacheClient.scala, app/utils/DateOfChangeHelper.scala, conf/logback.xml
app-config-production PR to remove any config that sets loggers to INFO level ->
- https://github.com/hmrc/app-config-production/pull/20802
No PRs have been created for AMLS EAB and AMP frontends. Both repositories only contain DEBUG level logs and so there isn't the need to set the root level to INFO
=> DDCYLS-4001 Converting info logs to warn where appropriate, outdated logging config

app/views/components/FeedbackSurveyLink.scala.html, app/views/confirmation/ConfirmationAmendmentView.scala.html, app/views/confirmation/ConfirmationNewView.scala.html, app/views/confirmation/ConfirmationNoFeeView.scala.html, app/views/confirmation/ConfirmationRenewalView.scala.html, test/views/confirmation/ConfirmationAmendmentViewSpec.scala, test/views/confirmation/ConfirmationBacsViewSpec.scala, test/views/confirmation/ConfirmationNewViewSpec.scala, test/views/confirmation/ConfirmationNoFeeViewSpec.scala, test/views/confirmation/ConfirmationRenewalViewSpec.scala, test/views/status/YourRegistrationViewSpec.scala
=> exit survey further work

app/views/confirmation/ConfirmationAmendmentView.scala.html, app/views/confirmation/ConfirmationNewView.scala.html, app/views/confirmation/ConfirmationNoFeeView.scala.html, app/views/confirmation/ConfirmationRenewalView.scala.html, test/views/confirmation/ConfirmationNoFeeViewSpec.scala
=> further exit survey work

app/models/tradingpremises/TradingPremises.scala, test/models/tradingpremises/TradingPremisesSpec.scala
=> DDCYLS-4479 Adding filter to filter out TradingPremises instances with 'Deleted' status tag

app/config/ApplicationConfig.scala, app/views/Layout.scala.html, app/views/components/FeedbackSurveyLink.scala.html, conf/application.conf, test/views/confirmation/ConfirmationBacsViewSpec.scala, test/views/confirmation/ConfirmationNoFeeViewSpec.scala, test/views/status/YourRegistrationViewSpec.scala
Please also merge: https://github.com/hmrc/app-config-base/pull/10003
The values that were removed from config were unused
=> DDCYLS-4533 Update exit survey config

app/services/cache/CacheOps.scala, app/services/cache/MongoCacheClient.scala, test/services/cache/CacheOpsSpec.scala, test/utils/AmlsSpec.scala
=> DDCYLS-4723 JSON double encryption fix

app/controllers/businessactivities/InvolvedInOtherController.scala, app/controllers/renewal/InvolvedInOtherController.scala, app/controllers/responsiblepeople/DetailedAnswersController.scala, app/controllers/responsiblepeople/ExperienceTrainingController.scala, test/controllers/businessactivities/InvolvedInOtherControllerSpec.scala, test/controllers/renewal/InvolvedInOtherControllerSpec.scala, test/controllers/responsiblepeople/DetailedAnswersControllerSpec.scala, test/controllers/responsiblepeople/ExperienceTrainingControllerSpec.scala
=> DDCYLS-4901 Adding error page when business activities not found

app/models/package.scala
Support for users (if any) who have previously selected these options
=> DDCYLS-3821 Add legacy support for country codes BQ, SH

app/forms/DateOfChangeFormProvider.scala, app/forms/hvd/CashPaymentFirstDateFormProvider.scala, app/forms/responsiblepeople/DateOfBirthFormProvider.scala, app/forms/responsiblepeople/LegalNameChangeDateFormProvider.scala, app/forms/responsiblepeople/PositionWithinBusinessStartDateFormProvider.scala, app/forms/responsiblepeople/RemoveResponsiblePersonFormProvider.scala, app/forms/supervision/SupervisionEndFormProvider.scala, app/forms/supervision/SupervisionStartFormProvider.scala, project/plugins.sbt, test/forms/DateOfChangeFormProviderSpec.scala, test/forms/hvd/CashPaymentFirstDateFormProviderSpec.scala, test/forms/responsiblepeople/DateOfBirthFormProviderSpec.scala, test/forms/responsiblepeople/LegalNameChangeDateFormProviderSpec.scala, test/forms/responsiblepeople/PositionWithinBusinessStartDateFormProviderSpec.scala, test/forms/supervision/SupervisionEndFormProviderSpec.scala, test/forms/supervision/SupervisionStartFormProviderSpec.scala, test/forms/tradingpremises/AgentNameFormProviderSpec.scala, test/forms/tradingpremises/RemoveTradingPremisesFormProviderSpec.scala
=> Coverting maxDate from val to def

app/views/tcsp/ServicesOfAnotherTCSPView.scala.html, app/views/tradingpremises/WhatYouNeedView.scala.html
=> Removed hyperlink from whitespace in TCSP view and What you need view

app/views/Layout.scala.html, build.sbt, conf/application.conf, test/resources/test.application.conf, test/utils/AmlsViewSpec.scala, test/views/applicationstatus/HowToPayViewSpec.scala, test/views/businessdetails/ActivityStartDateViewSpec.scala, test/views/businessdetails/ConfirmRegisteredOfficeOrMainPlaceViewSpec.scala, test/views/businessdetails/PreviouslyRegisteredViewSpec.scala, test/views/businessdetails/VATRegisteredViewSpec.scala, test/views/businessdetails/WhatYouNeedViewSpec.scala, test/views/businessmatching/CompanyRegistrationNumberViewSpec.scala, test/views/businessmatching/MsbServicesViewSpec.scala, test/views/businessmatching/PsrNumberViewSpec.scala, test/views/businessmatching/RegisterServicesViewSpec.scala, test/views/businessmatching/TypeOfBusinessViewSpec.scala, test/views/businessmatching/updateservice/remove/NeedMoreInformationViewSpec.scala
=> CSP config updates

conf/messages
=> DDCYLS-4606 Updating mismatched error message

app/views/hvd/CashPaymentText.scala.html, app/views/hvd/CashPaymentView.scala.html, conf/messages
=> Moved to complex question pattern and added details component

app/views/tcsp/ServicesOfAnotherTCSPView.scala.html, conf/messages
=> Missing fieldsets and legends for TCSP

app/views/businessdetails/CorrespondenceAddressNonUKView.scala.html, app/views/businessdetails/CorrespondenceAddressUKView.scala.html, app/views/components/forms/InputAddressLines.scala.html, app/views/components/forms/InputPostcode.scala.html, app/views/tradingpremises/WhereAreTradingPremisesView.scala.html
=> DDCYLS-4613. Added autocomplete attributes to all address pages

app/utils/renewal/CheckYourAnswersHelper.scala, app/views/renewal/AMLSTurnoverView.scala.html, build.sbt, conf/logback.xml, conf/messages, project/build.properties, project/plugins.sbt, test/controllers/renewal/AMLSTurnoverControllerSpec.scala, test/utils/renewal/CheckYourAnswersHelperSpec.scala, test/views/renewal/AMLSTurnoverViewSpec.scala
=> Added missing fieldsets and legends

app/controllers/NotificationController.scala, app/models/notifications/NotificationRow.scala, app/views/notifications/YourMessagesView.scala.html, conf/messages, test/views/notifications/YourMessagesViewSpec.scala
- Updating the secure comms table to have headers
- Adding an id to the table headers
- Removing use of heavy weight font throughout table
- Updating H1 to include business name
=> DDCYLS-4876 Secure comms table - captions and headers WCAG

app/controllers/tradingpremises/ActivityStartDateController.scala, app/utils/businessactivities/CheckYourAnswersHelper.scala, app/views/DateOfChangeView.scala.html, app/views/businessdetails/BusinessTelephoneView.scala.html, app/views/businessdetails/CorrespondenceAddressNonUKView.scala.html, app/views/businessdetails/CorrespondenceAddressUKView.scala.html, conf/logback.xml, test/controllers/businessactivities/SummaryControllerSpec.scala, test/controllers/businessdetails/ActivityStartDateControllerSpec.scala, test/controllers/tradingpremises/WhereAreTradingPremisesControllerSpec.scala, test/utils/businessactivities/CheckYourAnswersHelperSpec.scala, test/views/businessactivities/CheckYourAnswersViewSpec.scala, test/views/businessdetails/ActivityStartDateViewSpec.scala, test/views/renewal/AMLSTurnoverViewSpec.scala, test/views/tradingpremises/ActivityStartDateViewSpec.scala
- Implemented A11y fix for single item bullet list.
- Fixed CYA link redirecting users to the wrong page
- Fixed a few compilation warnings
=> DDCYLS-4644 | Fix single item bullet issue, incorrect link and warnings

app/views/payments/WaysToPayView.scala.html, conf/logback.xml, conf/messages
=> DDCYLS-4872. Missing fieldset and legends

app/controllers/businessactivities/SummaryController.scala, app/utils/businessactivities/CheckYourAnswersHelper.scala, test/utils/businessactivities/CheckYourAnswersHelperSpec.scala, test/views/businessactivities/CheckYourAnswersViewSpec.scala
The title of this page was made static in the last PR, so now the CYA helper does not require logic regarding business types
=> DDCYLS-4738 Updated CYA logic following page change

app/views/components/ServicesSidebar.scala.html, test/views/registrationamendment/RegistrationAmendmentViewSpec.scala, test/views/registrationprogress/RegistrationProgressViewSpec.scala, test/views/renewal/RenewalProgressViewSpec.scala
=> DDCYLS-4602. Updated layout of About your business page

app/views/renewal/CashPaymentsCustomersNotMetView.scala.html, conf/messages, test/views/renewal/CashPaymentsCustomersNotMetViewSpec.scala
=> Missing fieldsets and legends added

app/controllers/tradingpremises/WhereAreTradingPremisesController.scala
=> DDCYLS-4885 Updating hardcoded index value to parameter value

app/views/responsiblepeople/LegalNameView.scala.html
=> updated LegalNameView content

app/views/confirmation/components/ConfirmationDetailsView.scala.html
=> DDCYLS-4871 Removing hidden span tag and content 

conf/messages
=> updated error message

README.md, conf/messages
=> Ddcly 4863

app/config/ApplicationConfig.scala, app/views/businessactivities/NCARegisteredView.scala.html, app/views/businessmatching/CompanyRegistrationNumberView.scala.html, app/views/tcsp/ServicesOfAnotherTCSPView.scala.html, conf/messages
=> DDCYLS-3551. Content change for pre-application crn page

app/views/payments/BankDetailsView.scala.html, test/views/payments/BankDetailsViewSpec.scala
=> DDCYLS-4873: Updated BACS page with the summary list markup

app/controllers/BacsConfirmationController.scala, app/controllers/StatusController.scala, app/controllers/testonly/TestOnlyController.scala, app/views/confirmation/ConfirmationBacsView.scala.html, app/views/confirmation/ConfirmationNoFeeView.scala.html, app/views/status/YourRegistrationView.scala.html, conf/messages, test/controllers/BacsConfirmationControllerSpec.scala, test/controllers/StatusControllerSpec.scala, test/views/confirmation/ConfirmationBacsViewSpec.scala, test/views/confirmation/ConfirmationNoFeeViewSpec.scala, test/views/status/YourRegistrationViewSpec.scala
… registration [renewal] & update information confirmation pages).
Updated Panels to include the AMLS reference on registration and renewal journeys. Updated some of the main body content on registration, re registration [renewal] & update information confirmation pages. Removal of continue button replaced by a 'Go to Your Registration' link on registration journey to navigate user to dashboard. Removal of continue button replaced by a 'Return to Your Registration' link on renewal journey to navigate user to dashboard. Removal of the exit survey from all AMLS Dashboards (different dashboards for each status).
=> DDCYLS-5011 - Update AMLS confirmation pages

app/controllers/businessmatching/updateservice/remove/RemoveBusinessTypesController.scala, app/controllers/responsiblepeople/PositionWithinBusinessController.scala, app/models/responsiblepeople/PositionWithinBusiness.scala, app/views/businessmatching/updateservice/add/MsbSubSectorsView.scala.html, app/views/businessmatching/updateservice/remove/RemoveActivitiesView.scala.html, app/views/renewal/InvolvedInOtherView.scala.html, app/views/responsiblepeople/KnownByView.scala.html, app/views/responsiblepeople/PositionWithinBusinessView.scala.html, test/controllers/renewal/InvolvedInOtherControllerSpec.scala, test/views/businessmatching/updateservice/remove/RemoveActivitiesViewSpec.scala, test/views/renewal/InvolvedInOtherViewSpec.scala, test/views/responsiblepeople/KnownByViewSpec.scala, test/views/responsiblepeople/PositionWithinBusinessViewSpec.scala
=> DDCYLS-4653 Error summary does not take user to first input

app/forms/responsiblepeople/SelfAssessmentRegisteredFormProvider.scala, test/forms/responsiblepeople/SelfAssessmentRegisteredFormProviderSpec.scala
=> DDCYLS-4676 Validation of UTR does not allow spaces

app/forms/businessdetails/VATRegisteredFormProvider.scala, test/forms/businessdetails/VATRegisteredFormProviderSpec.scala
=> DDCYLS-4608  - Validation of VAT Ref does not allow spaces 

app/forms/bankdetails/BankAccountIBANNumberFormProvider.scala, app/forms/mappings/Mappings.scala, test/forms/bankdetails/BankAccountIBANNumberFormProviderSpec.scala
=> DDCYLS-4639 Validation of IBAN does not allow spaces

app/forms/responsiblepeople/PersonNonUKPassportFormProvider.scala, app/forms/responsiblepeople/PersonUKPassportFormProvider.scala, test/forms/responsiblepeople/PersonNonUKPassportFormProviderSpec.scala, test/forms/responsiblepeople/PersonUKPassportFormProviderSpec.scala
Implementing method to trim and remove whitespace on passport number validations
=> Ddcyls 4657

app/utils/CheckYourAnswersHelperFunctions.scala, app/utils/bankdetails/CheckYourAnswersHelper.scala, app/utils/businessactivities/CheckYourAnswersHelper.scala, app/utils/businessdetails/CheckYourAnswersHelper.scala, app/utils/businessmatching/CheckYourAnswersHelper.scala, app/utils/hvd/CheckYourAnswersHelper.scala, app/utils/msb/CheckYourAnswersHelper.scala, app/utils/renewal/CheckYourAnswersHelper.scala, app/utils/responsiblepeople/CheckYourAnswersHelper.scala, app/utils/supervision/CheckYourAnswersHelper.scala, app/utils/tcsp/CheckYourAnswersHelper.scala, app/utils/tradingpremises/CheckYourAnswersHelper.scala, conf/messages, test/controllers/hvd/SummaryControllerSpec.scala
=> DDCYLS-4642  - Check your answers pages to include visually hidden

app/forms/mappings/LocalDateFormatter.scala, app/forms/mappings/Mappings.scala, test/forms/businessdetails/ActivityStartDateFormProviderSpec.scala
=> DDCYLS-4605 Validation of date does not allow spaces

app/forms/tcsp/AnotherTCSPSupervisionFormProvider.scala, test/forms/tcsp/AnotherTCSPSupervisionFormProviderSpec.scala
=> DDCYLS-4728 Validation of MLR number

app/forms/businessmatching/PSRNumberFormProvider.scala, test/forms/businessmatching/PSRNumberFormProviderSpec.scala
Implementing method to trim and remove white space on PSR validation
=> DDCYLS-4884 : PSR does not allow spaces 

app/forms/mappings/AddressMappings.scala, app/forms/mappings/Mappings.scala, test/forms/behaviours/AddressFieldBehaviours.scala
=> DDCYLS 4614 - [AMLS] Validation of Postcode does not allow spaces 

app/forms/bankdetails/BankAccountNonUKFormProvider.scala, test/forms/bankdetails/BankAccountNonUKFormProviderSpec.scala
=> Ddcyls 4648 - Validation of non-UK bank account number does not allow spaces

app/forms/businessmatching/CompanyRegistrationNumberFormProvider.scala, test/forms/businessmatching/CompanyRegistrationNumberFormProviderSpec.scala
=> DDCYLS-4599 - Amending whitespace validation on company reg number

app/views/asp/ServicesOfBusinessView.scala.html, app/views/hvd/ProductsView.scala.html, app/views/msb/MoneySourcesView.scala.html, app/views/renewal/HowCashPaymentsReceivedView.scala.html, app/views/renewal/MoneySourcesView.scala.html, app/views/responsiblepeople/PositionWithinBusinessView.scala.html, app/views/supervision/WhichProfessionalBodyView.scala.html, app/views/tcsp/ProvidedServicesView.scala.html, app/views/tcsp/ServiceProviderTypesView.scala.html
A number of pages have missing fieldsets and legends for the checkbox answers.
=> DDCYLS-4660 - Missing fieldsets and legends (checkboxes)

app/views/declaration/AddPersonView.scala.html, app/views/hvd/ExpectToReceiveView.scala.html, test/views/declaration/AddPersonViewSpec.scala
Adding a fieldset to checkboxes on the add person and expect to receive screens.
=> DDCYLS-5619 - Adding a fieldset to checkboxes on the add person and expect to receive screens

conf/messages
=> DDCYLS-3828 - Pre-application check your answers update

app/assets/stylesheets/application.scss, app/views/status/YourRegistrationView.scala.html, test/views/status/YourRegistrationViewSpec.scala
=> DDCYLS-4857 - Status page spacing [P2]

app/controllers/withdrawal/WithdrawalCheckYourAnswersController.scala, app/controllers/withdrawal/WithdrawalReasonController.scala, app/models/withdrawal/WithdrawalReason.scala, app/utils/withdrawals/CheckYourAnswersHelper.scala, app/views/withdrawal/WithdrawalCheckYourAnswersView.scala.html, conf/app.routes, conf/messages, project/AppDependencies.scala, test/controllers/withdrawal/WithdrawalCheckYourAnswersControllerSpec.scala, test/controllers/withdrawal/WithdrawalReasonControllerSpec.scala
- Clear Summary: Displays the selected withdrawal reason along with any additional details, ensuring users can easily review their choices.
- Final Review Step: Provides users with a last opportunity to confirm their information before final submission, reducing the likelihood of errors and improving overall process clarity.
=> DDCYLS-5621 - Implemented Check Your Answers (CYA) Page for Withdrawal Journey

app/controllers/RegistrationProgressController.scala, app/controllers/declaration/WhoIsRegisteringController.scala, app/controllers/renewal/RenewalProgressController.scala, app/services/RenewalService.scala, app/services/SectionsProvider.scala, app/utils/BusinessName.scala, app/utils/DeclarationHelper.scala, build.sbt, conf/app.routes, test/controllers/RegistrationProgressControllerSpec.scala, test/controllers/declaration/WhoIsRegisteringControllerSpec.scala, test/controllers/renewal/RenewalProgressControllerSpec.scala, test/services/RenewalServiceSpec.scala
Signed-off-by: paweldigital <173694350+paweldigital@users.noreply.github.com>
=> DDCYLS-5873: fix renewal loop

app/controllers/businessmatching/PSRNumberController.scala, test/controllers/businessmatching/PSRNumberControllerSpec.scala
=> DDCYLS-5785 - PSR number FIX 

app/controllers/businessmatching/PSRNumberController.scala, test/controllers/businessmatching/PSRNumberControllerSpec.scala
=> DDCYLS-5785-fix - prepopulates user entered PSR correctly

README.md
=> DDCYLS-6374 - ReadMe update

app/controllers/deregister/DeregistrationConfirmationController.scala, app/views/deregister/DeregistrationConfirmationView.scala.html, test/views/deregister/DeregistrationConfirmationViewSpec.scala
=> DDCYLS-6368: Deregistration Confirmation Reason handled dynamically.

build.sbt, project/AppDependencies.scala
ch.qos.logback:logback-core dependency added for the runtime issue and upgraded the play-frontend-hmrc dependency
=> DDCYLS-6428: ch.qos.logback:logback-core dependency added for the runtime issue

app/views/responsiblepeople/FitAndProperView.scala.html, conf/messages, project/AppDependencies.scala
Updating fit and proper view content
=> DDCYLS-5531 - Updating content on fit and proper view

app/controllers/LandingController.scala, app/controllers/deregister/DeregistrationConfirmationController.scala, app/controllers/responsiblepeople/ExperienceTrainingController.scala, app/services/CustomAttributeProvider.scala, app/services/StatusService.scala, precheck.sh, project/AppDependencies.scala, test/views/deregister/DeregistrationConfirmationViewSpec.scala
adding precheck sh and format fixes
=> DDCYLS-6655 - Adding precheck file
